# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.AbstractMigrationEventPayload do
  @moduledoc """
  Represents a single action details in MigrationEventAuditDetails
  """

  @derive [Poison.Encoder]
  defstruct [
    :actionType,
    :actionDate,
    :actionNote,
    :userName
  ]

  @type t :: %__MODULE__{
          :actionType => ExWorldCheck.Model.MigrationAuditActionType.t(),
          :actionDate => DateTime.t(),
          :actionNote => String.t(),
          :userName => String.t()
        }
end

defimpl Poison.Decoder, for: ExWorldCheck.Model.AbstractMigrationEventPayload do
  import ExWorldCheck.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:actionType, :struct, ExWorldCheck.Model.MigrationAuditActionType, options)
  end
end
