# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.AbstractAuditDetails do
  @moduledoc """
  Abstract case audit event details object
  """

  @derive [Poison.Encoder]
  defstruct [
    :detailsType
  ]

  @type t :: %__MODULE__{
          :detailsType => String.t()
        }
end

defimpl Poison.Decoder, for: ExWorldCheck.Model.AbstractAuditDetails do
  def decode(value, _options) do
    value
  end
end
