# NOTE: This file is auto generated by OpenAPI Generator 7.13.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.AbstractMigrationEventPayload do
  @moduledoc """
  Represents a single action details in MigrationEventAuditDetails
  """

  @derive JSON.Encoder
  defstruct [
    :actionType,
    :actionDate,
    :actionNote,
    :userName
  ]

  @type t :: %__MODULE__{
          :actionType => ExWorldCheck.Model.MigrationAuditActionType.t(),
          :actionDate => DateTime.t(),
          :actionNote => String.t(),
          :userName => String.t()
        }

  alias ExWorldCheck.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:actionType, :struct, ExWorldCheck.Model.MigrationAuditActionType)
  end
end
