# NOTE: This file is auto generated by OpenAPI Generator 7.13.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.AbstractField do
  @moduledoc """
  Generic Field representing a Custom Field or a Secondary Field.
  """

  @derive JSON.Encoder
  defstruct [
    :typeId
  ]

  @type t :: %__MODULE__{
          :typeId => String.t()
        }

  def decode(value) do
    value
  end
end
