# NOTE: This file is auto generated by OpenAPI Generator 7.13.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.AbstractAuditDetails do
  @moduledoc """
  Abstract case audit event details object
  """

  @derive JSON.Encoder
  defstruct [
    :detailsType
  ]

  @type t :: %__MODULE__{
          :detailsType => String.t()
        }

  def decode(value) do
    value
  end
end
