# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.AddNoteToCaseAuditDetailsAllOf do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :caseID,
    :caseName,
    :assignorName,
    :assigneeName,
    :assigneeEmail,
    :title,
    :body
  ]

  @type t :: %__MODULE__{
          :caseID => String.t(),
          :caseName => String.t(),
          :assignorName => String.t(),
          :assigneeName => String.t(),
          :assigneeEmail => String.t(),
          :title => String.t(),
          :body => String.t()
        }
end

defimpl Poison.Decoder, for: ExWorldCheck.Model.AddNoteToCaseAuditDetailsAllOf do
  def decode(value, _options) do
    value
  end
end
