# NOTE: This file is auto generated by OpenAPI Generator 7.13.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.AddNoteToCaseAuditDetails do
  @moduledoc """
  Audit details for action raised when a Case note is set. Extends [AbstractAuditDetails](#AbstractAuditDetails).
  """

  @derive JSON.Encoder
  defstruct [
    :detailsType,
    :caseID,
    :caseName,
    :assignorName,
    :assigneeName,
    :assigneeEmail,
    :title,
    :body
  ]

  @type t :: %__MODULE__{
          :detailsType => String.t(),
          :caseID => String.t(),
          :caseName => String.t(),
          :assignorName => String.t(),
          :assigneeName => String.t(),
          :assigneeEmail => String.t(),
          :title => String.t(),
          :body => String.t()
        }

  def decode(value) do
    value
  end
end
