# NOTE: This file is auto generated by OpenAPI Generator 7.13.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.Address do
  @moduledoc """

  """

  @derive JSON.Encoder
  defstruct [
    :city,
    :country,
    :postCode,
    :region,
    :street
  ]

  @type t :: %__MODULE__{
          :city => String.t() | nil,
          :country => ExWorldCheck.Model.Country.t() | nil,
          :postCode => String.t() | nil,
          :region => String.t() | nil,
          :street => String.t() | nil
        }

  alias ExWorldCheck.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:country, :struct, ExWorldCheck.Model.Country)
  end
end
