# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.Address do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :city,
    :country,
    :postCode,
    :region,
    :street
  ]

  @type t :: %__MODULE__{
          :city => String.t() | nil,
          :country => ExWorldCheck.Model.Country.t() | nil,
          :postCode => String.t() | nil,
          :region => String.t() | nil,
          :street => String.t() | nil
        }
end

defimpl Poison.Decoder, for: ExWorldCheck.Model.Address do
  import ExWorldCheck.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:country, :struct, ExWorldCheck.Model.Country, options)
  end
end
