# NOTE: This file is auto generated by OpenAPI Generator 7.13.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.ArticlesReviewDate do
  @moduledoc """
  Date and time when all articles were reviewed.
  """

  @derive JSON.Encoder
  defstruct [
    :dateReviewed
  ]

  @type t :: %__MODULE__{
          :dateReviewed => DateTime.t()
        }

  def decode(value) do
    value
  end
end
