# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.ArticlesReviewDate do
  @moduledoc """
  Date and time when all articles were reviewed.
  """

  @derive [Poison.Encoder]
  defstruct [
    :dateReviewed
  ]

  @type t :: %__MODULE__{
          :dateReviewed => DateTime.t()
        }
end

defimpl Poison.Decoder, for: ExWorldCheck.Model.ArticlesReviewDate do
  def decode(value, _options) do
    value
  end
end
