# NOTE: This file is auto generated by OpenAPI Generator 7.13.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.AssignCaseToUserAuditDetails do
  @moduledoc """
  Audit details for ASSIGN_CASE action raised when a Case is assigned to a user. Extends [AbstractAuditDetails](#AbstractAuditDetails).
  """

  @derive JSON.Encoder
  defstruct [
    :detailsType,
    :assigneeUserName,
    :assigneeUserId,
    :assigneeEmail,
    :caseName,
    :assignorName
  ]

  @type t :: %__MODULE__{
          :detailsType => String.t(),
          :assigneeUserName => String.t(),
          :assigneeUserId => String.t(),
          :assigneeEmail => String.t(),
          :caseName => String.t(),
          :assignorName => String.t()
        }

  def decode(value) do
    value
  end
end
