# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.AuditSearchResponse do
  @moduledoc """
  Audit Search Response Object
  """

  @derive [Poison.Encoder]
  defstruct [
    :query,
    :sort,
    :pagination,
    :totalResultCount,
    :results
  ]

  @type t :: %__MODULE__{
          :query => String.t() | nil,
          :sort => [ExWorldCheck.Model.SortCriterion.t()] | nil,
          :pagination => ExWorldCheck.Model.PaginationResponse.t() | nil,
          :totalResultCount => integer(),
          :results => [ExWorldCheck.Model.AuditEvent.t()] | nil
        }
end

defimpl Poison.Decoder, for: ExWorldCheck.Model.AuditSearchResponse do
  import ExWorldCheck.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:sort, :list, ExWorldCheck.Model.SortCriterion, options)
    |> deserialize(:pagination, :struct, ExWorldCheck.Model.PaginationResponse, options)
    |> deserialize(:results, :list, ExWorldCheck.Model.AuditEvent, options)
  end
end
