# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.AuditEventActionType do
  @moduledoc """
  Type of action that caused the audit event to be created.
  """

  @derive [Poison.Encoder]
  defstruct []

  @type t :: %__MODULE__{}
end

defimpl Poison.Decoder, for: ExWorldCheck.Model.AuditEventActionType do
  def decode(value, _options) do
    value
  end
end
