# NOTE: This file is auto generated by OpenAPI Generator 7.13.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.AuditEventSourceType do
  @moduledoc """
  Enumeration of available audit event sources types.  Possible types of audit event sources are:  * DESKTOP - Signifies the event is originating from DESKTOP/UI * DESKTOP_BULK - Signifies the event is originating from DESKTOP/UI Bulk actions * API - Signifies the event is originating from API * API_BULK - Signifies the event is originating from API Bulk actions * DESKTOP_BATCH - Signifies the event is originating from DESKTOP/UI Batch screening * API_BATCH - Signifies the event is originating from API Batch screening via saveAndScreen endpoint * OGS - Signifies the event is originating from ongoing screening * UNKNOWN - Signifies the event source is unknown 
  """

  @derive JSON.Encoder
  defstruct []

  @type t :: %__MODULE__{}

  def decode(value) do
    value
  end
end
