# NOTE: This file is auto generated by OpenAPI Generator 7.13.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.BatchDetail do
  @moduledoc """
  Batch detail referenced from GenericCaseAuditDetails
  """

  @derive JSON.Encoder
  defstruct [
    :batchId,
    :batchName
  ]

  @type t :: %__MODULE__{
          :batchId => String.t(),
          :batchName => String.t()
        }

  def decode(value) do
    value
  end
end
