# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.CaseSummaryFilter do
  @moduledoc """
  Defines search criteria, sorting and items count in the response.
  """

  @derive [Poison.Encoder]
  defstruct [
    :query,
    :sort,
    :cursorOptions
  ]

  @type t :: %__MODULE__{
          :query => String.t() | nil,
          :sort => [ExWorldCheck.Model.SortCriterion.t()] | nil,
          :cursorOptions => ExWorldCheck.Model.CursorOptions.t() | nil
        }
end

defimpl Poison.Decoder, for: ExWorldCheck.Model.CaseSummaryFilter do
  import ExWorldCheck.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:sort, :list, ExWorldCheck.Model.SortCriterion, options)
    |> deserialize(:cursorOptions, :struct, ExWorldCheck.Model.CursorOptions, options)
  end
end
