# NOTE: This file is auto generated by OpenAPI Generator 7.13.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.CaseBulkResponse do
  @moduledoc """
  Cases Archived / Unarchived Bulk Response
  """

  @derive JSON.Encoder
  defstruct [
    :statuses
  ]

  @type t :: %__MODULE__{
          :statuses => [ExWorldCheck.Model.CaseBulkStatus.t()]
        }

  alias ExWorldCheck.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:statuses, :list, ExWorldCheck.Model.CaseBulkStatus)
  end
end
