# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.CaseReference do
  @moduledoc """
  Container of 'caseId' and 'caseSystemId'.
  """

  @derive [Poison.Encoder]
  defstruct [
    :caseSystemId,
    :caseId
  ]

  @type t :: %__MODULE__{
          :caseSystemId => String.t(),
          :caseId => String.t()
        }
end

defimpl Poison.Decoder, for: ExWorldCheck.Model.CaseReference do
  def decode(value, _options) do
    value
  end
end
