# NOTE: This file is auto generated by OpenAPI Generator 7.13.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.CaseRatingRequest do
  @moduledoc """
  The object representing a case rating.
  """

  @derive JSON.Encoder
  defstruct [
    :caseRating,
    :reason
  ]

  @type t :: %__MODULE__{
          :caseRating => String.t(),
          :reason => String.t() | nil
        }

  def decode(value) do
    value
  end
end
