# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.CaseRelationshipRequest do
  @moduledoc """
  Request to hold pagination details for listing case relationships.
  """

  @derive [Poison.Encoder]
  defstruct [
    :pagination
  ]

  @type t :: %__MODULE__{
          :pagination => ExWorldCheck.Model.Pagination.t() | nil
        }
end

defimpl Poison.Decoder, for: ExWorldCheck.Model.CaseRelationshipRequest do
  import ExWorldCheck.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:pagination, :struct, ExWorldCheck.Model.Pagination, options)
  end
end
