# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.CaseBulkResponse do
  @moduledoc """
  Cases Archived / Unarchived Bulk Response
  """

  @derive [Poison.Encoder]
  defstruct [
    :statuses
  ]

  @type t :: %__MODULE__{
          :statuses => [ExWorldCheck.Model.CaseBulkStatus.t()]
        }
end

defimpl Poison.Decoder, for: ExWorldCheck.Model.CaseBulkResponse do
  import ExWorldCheck.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:statuses, :list, ExWorldCheck.Model.CaseBulkStatus, options)
  end
end
