# NOTE: This file is auto generated by OpenAPI Generator 7.13.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.CaseBulkStatus do
  @moduledoc """
  Case Bulk Status
  """

  @derive JSON.Encoder
  defstruct [
    :caseSystemId,
    :success,
    :errors
  ]

  @type t :: %__MODULE__{
          :caseSystemId => String.t(),
          :success => boolean(),
          :errors => [ExWorldCheck.Model.Error.t()] | nil
        }

  alias ExWorldCheck.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:errors, :list, ExWorldCheck.Model.Error)
  end
end
