# NOTE: This file is auto generated by OpenAPI Generator 7.13.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.CaseRatingResponse do
  @moduledoc """
  Retrieved case rating for a Case data response. 
  """

  @derive JSON.Encoder
  defstruct [
    :caseRating,
    :reason,
    :createdDate,
    :createdBy
  ]

  @type t :: %__MODULE__{
          :caseRating => String.t() | nil,
          :reason => String.t() | nil,
          :createdDate => DateTime.t() | nil,
          :createdBy => String.t() | nil
        }

  def decode(value) do
    value
  end
end
