# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.CaseAllOf do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :caseSystemId,
    :caseScreeningState,
    :lifecycleState,
    :assignee,
    :creator,
    :modifier,
    :creationDate,
    :modificationDate,
    :outstandingActions,
    :lastScreenedDatesByProviderType,
    :providerTypeDetails,
    :aggregatedResultSummaries
  ]

  @type t :: %__MODULE__{
          :caseSystemId => String.t() | nil,
          :caseScreeningState => %{optional(String.t()) => String.t()} | nil,
          :lifecycleState => String.t() | nil,
          :assignee => ExWorldCheck.Model.UserSummary.t() | nil,
          :creator => ExWorldCheck.Model.UserSummary.t() | nil,
          :modifier => ExWorldCheck.Model.UserSummary.t() | nil,
          :creationDate => DateTime.t() | nil,
          :modificationDate => DateTime.t() | nil,
          :outstandingActions => boolean() | nil,
          :lastScreenedDatesByProviderType => %{optional(String.t()) => DateTime.t()} | nil,
          :providerTypeDetails => ExWorldCheck.Model.ProviderTypeDetails.t() | nil,
          :aggregatedResultSummaries => ExWorldCheck.Model.CaseResultSummaries.t() | nil
        }
end

defimpl Poison.Decoder, for: ExWorldCheck.Model.CaseAllOf do
  import ExWorldCheck.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:assignee, :struct, ExWorldCheck.Model.UserSummary, options)
    |> deserialize(:creator, :struct, ExWorldCheck.Model.UserSummary, options)
    |> deserialize(:modifier, :struct, ExWorldCheck.Model.UserSummary, options)
    |> deserialize(:providerTypeDetails, :struct, ExWorldCheck.Model.ProviderTypeDetails, options)
    |> deserialize(
      :aggregatedResultSummaries,
      :struct,
      ExWorldCheck.Model.CaseResultSummaries,
      options
    )
  end
end
