# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.CaseRelationshipResponse do
  @moduledoc """
  The result set of relationships between cases.
  """

  @derive [Poison.Encoder]
  defstruct [
    :pagination,
    :totalResultCount,
    :results
  ]

  @type t :: %__MODULE__{
          :pagination => ExWorldCheck.Model.PaginationResponseDetails.t() | nil,
          :totalResultCount => integer() | nil,
          :results => [ExWorldCheck.Model.RelationshipIdentifiers.t()] | nil
        }
end

defimpl Poison.Decoder, for: ExWorldCheck.Model.CaseRelationshipResponse do
  import ExWorldCheck.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:pagination, :struct, ExWorldCheck.Model.PaginationResponseDetails, options)
    |> deserialize(:results, :list, ExWorldCheck.Model.RelationshipIdentifiers, options)
  end
end
