# NOTE: This file is auto generated by OpenAPI Generator 7.13.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.CaseReference do
  @moduledoc """
  Container of 'caseId' and 'caseSystemId'.
  """

  @derive JSON.Encoder
  defstruct [
    :caseSystemId,
    :caseId
  ]

  @type t :: %__MODULE__{
          :caseSystemId => String.t(),
          :caseId => String.t()
        }

  def decode(value) do
    value
  end
end
