# NOTE: This file is auto generated by OpenAPI Generator 7.13.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.CaseDetailsCollection do
  @moduledoc """
  Container of cases, that is used in scope of creation operation.
  """

  @derive JSON.Encoder
  defstruct [
    :groupId,
    :providerTypes,
    :nameTransposition,
    :caseScreeningState,
    :cases
  ]

  @type t :: %__MODULE__{
          :groupId => String.t(),
          :providerTypes => [ExWorldCheck.Model.ProviderType.t()],
          :nameTransposition => boolean() | nil,
          :caseScreeningState => %{optional(String.t()) => String.t()} | nil,
          :cases => [ExWorldCheck.Model.CaseDetails.t()]
        }

  alias ExWorldCheck.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:providerTypes, :list, ExWorldCheck.Model.ProviderType)
    |> Deserializer.deserialize(:cases, :list, ExWorldCheck.Model.CaseDetails)
  end
end
