# NOTE: This file is auto generated by OpenAPI Generator 7.13.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.CaseTemplateResponse do
  @moduledoc """
  Case template, containing metadata required by the client to construct a valid Case
  """

  @derive JSON.Encoder
  defstruct [
    :groupScreeningType,
    :groupId,
    :customFields,
    :secondaryFieldsByProvider,
    :mandatoryProviderTypes
  ]

  @type t :: %__MODULE__{
          :groupScreeningType => ExWorldCheck.Model.GroupScreeningType.t(),
          :groupId => String.t(),
          :customFields => [ExWorldCheck.Model.FieldDefinition.t()] | nil,
          :secondaryFieldsByProvider =>
            %{optional(String.t()) => ExWorldCheck.Model.SecondaryFieldsByEntity.t()} | nil,
          :mandatoryProviderTypes => [ExWorldCheck.Model.ProviderType.t()] | nil
        }

  alias ExWorldCheck.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :groupScreeningType,
      :struct,
      ExWorldCheck.Model.GroupScreeningType
    )
    |> Deserializer.deserialize(:customFields, :list, ExWorldCheck.Model.FieldDefinition)
    |> Deserializer.deserialize(
      :secondaryFieldsByProvider,
      :map,
      ExWorldCheck.Model.SecondaryFieldsByEntity
    )
    |> Deserializer.deserialize(:mandatoryProviderTypes, :list, ExWorldCheck.Model.ProviderType)
  end
end
