# NOTE: This file is auto generated by OpenAPI Generator 7.13.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.CaseBulkLinkRequest do
  @moduledoc """
  Case Bulk Link Request
  """

  @derive JSON.Encoder
  defstruct [
    :caseSystemId,
    :relatedCaseSystemIds
  ]

  @type t :: %__MODULE__{
          :caseSystemId => String.t(),
          :relatedCaseSystemIds => [String.t()]
        }

  def decode(value) do
    value
  end
end
