# NOTE: This file is auto generated by OpenAPI Generator 7.13.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.CaseRelationshipResponse do
  @moduledoc """
  The result set of relationships between cases.
  """

  @derive JSON.Encoder
  defstruct [
    :pagination,
    :totalResultCount,
    :results
  ]

  @type t :: %__MODULE__{
          :pagination => ExWorldCheck.Model.PaginationResponseDetails.t() | nil,
          :totalResultCount => integer() | nil,
          :results => [ExWorldCheck.Model.RelationshipIdentifiers.t()] | nil
        }

  alias ExWorldCheck.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :pagination,
      :struct,
      ExWorldCheck.Model.PaginationResponseDetails
    )
    |> Deserializer.deserialize(:results, :list, ExWorldCheck.Model.RelationshipIdentifiers)
  end
end
