# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.CaseBulkLinkRequestCollection do
  @moduledoc """
  A request body on Bulk Update Case Links
  """

  @derive [Poison.Encoder]
  defstruct [
    :link,
    :relationshipType,
    :caseSystemIds,
    :note
  ]

  @type t :: %__MODULE__{
          :link => boolean(),
          :relationshipType => String.t(),
          :caseSystemIds => [ExWorldCheck.Model.CaseBulkLinkRequest.t()],
          :note => String.t() | nil
        }
end

defimpl Poison.Decoder, for: ExWorldCheck.Model.CaseBulkLinkRequestCollection do
  import ExWorldCheck.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:caseSystemIds, :list, ExWorldCheck.Model.CaseBulkLinkRequest, options)
  end
end
