# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.CaseSummaryFilterResponse do
  @moduledoc """
  Filter the response
  """

  @derive [Poison.Encoder]
  defstruct [
    :query,
    :sort
  ]

  @type t :: %__MODULE__{
          :query => String.t() | nil,
          :sort => [ExWorldCheck.Model.SortCriterion.t()] | nil
        }
end

defimpl Poison.Decoder, for: ExWorldCheck.Model.CaseSummaryFilterResponse do
  import ExWorldCheck.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:sort, :list, ExWorldCheck.Model.SortCriterion, options)
  end
end
