# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.CaseSummaryFilterAllOf do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :cursorOptions
  ]

  @type t :: %__MODULE__{
          :cursorOptions => ExWorldCheck.Model.CursorOptions.t() | nil
        }
end

defimpl Poison.Decoder, for: ExWorldCheck.Model.CaseSummaryFilterAllOf do
  import ExWorldCheck.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:cursorOptions, :struct, ExWorldCheck.Model.CursorOptions, options)
  end
end
