# NOTE: This file is auto generated by OpenAPI Generator 7.13.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.CaseBulkArchiveRequest do
  @moduledoc """
  A request body on Bulk Update Archive States
  """

  @derive JSON.Encoder
  defstruct [
    :archive,
    :caseSystemIds,
    :note
  ]

  @type t :: %__MODULE__{
          :archive => boolean(),
          :caseSystemIds => [String.t()],
          :note => String.t() | nil
        }

  def decode(value) do
    value
  end
end
