# NOTE: This file is auto generated by OpenAPI Generator 7.13.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.CaseSummaryFilter do
  @moduledoc """
  Defines search criteria, sorting and items count in the response.
  """

  @derive JSON.Encoder
  defstruct [
    :query,
    :sort,
    :cursorOptions
  ]

  @type t :: %__MODULE__{
          :query => String.t() | nil,
          :sort => [ExWorldCheck.Model.SortCriterion.t()] | nil,
          :cursorOptions => ExWorldCheck.Model.CursorOptions.t() | nil
        }

  alias ExWorldCheck.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:sort, :list, ExWorldCheck.Model.SortCriterion)
    |> Deserializer.deserialize(:cursorOptions, :struct, ExWorldCheck.Model.CursorOptions)
  end
end
