# NOTE: This file is auto generated by OpenAPI Generator 7.13.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.CaseRelationshipRequest do
  @moduledoc """
  Request to hold pagination details for listing case relationships.
  """

  @derive JSON.Encoder
  defstruct [
    :pagination
  ]

  @type t :: %__MODULE__{
          :pagination => ExWorldCheck.Model.Pagination.t() | nil
        }

  alias ExWorldCheck.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:pagination, :struct, ExWorldCheck.Model.Pagination)
  end
end
