# NOTE: This file is auto generated by OpenAPI Generator 7.13.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.CaseSearchUserSummary do
  @moduledoc """

  """

  @derive JSON.Encoder
  defstruct [
    :fullName
  ]

  @type t :: %__MODULE__{
          :fullName => String.t()
        }

  def decode(value) do
    value
  end
end
