# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.CaseDetails do
  @moduledoc """
  Representation of a single case that is used for case creation operation. Defines Case data that can be sent when creating a new Case. 
  """

  @derive [Poison.Encoder]
  defstruct [
    :caseId,
    :entityType,
    :name,
    :customFields,
    :secondaryFields
  ]

  @type t :: %__MODULE__{
          :caseId => String.t() | nil,
          :entityType => String.t(),
          :name => String.t(),
          :customFields => [ExWorldCheck.Model.Field.t()] | nil,
          :secondaryFields => [ExWorldCheck.Model.Field.t()] | nil
        }
end

defimpl Poison.Decoder, for: ExWorldCheck.Model.CaseDetails do
  import ExWorldCheck.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:customFields, :list, ExWorldCheck.Model.Field, options)
    |> deserialize(:secondaryFields, :list, ExWorldCheck.Model.Field, options)
  end
end
