# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.ChangedCaseMediaCheckSmartFilterPreferenceAuditDetails do
  @moduledoc """
  Audit details which contains details of changing the state of MediaCheck smart filter. Extends [AbstractAuditDetails](#AbstractAuditDetails).
  """

  @derive [Poison.Encoder]
  defstruct [
    :detailsType,
    :casePreferenceType,
    :status,
    :dateTimeModification
  ]

  @type t :: %__MODULE__{
          :detailsType => String.t(),
          :casePreferenceType => ExWorldCheck.Model.CasePreferenceType.t(),
          :status => String.t(),
          :dateTimeModification => DateTime.t()
        }
end

defimpl Poison.Decoder,
  for: ExWorldCheck.Model.ChangedCaseMediaCheckSmartFilterPreferenceAuditDetails do
  import ExWorldCheck.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:casePreferenceType, :struct, ExWorldCheck.Model.CasePreferenceType, options)
  end
end
