# NOTE: This file is auto generated by OpenAPI Generator 7.13.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.ChangeCaseScreeningStateAuditDetails do
  @moduledoc """
  Audit details for CHANGE_CASE_SCREENING_STATE action raised when the Case Screening state has changed. Extends [AbstractAuditDetails](#AbstractAuditDetails).
  """

  @derive JSON.Encoder
  defstruct [
    :detailsType,
    :dateTimeModification,
    :caseScreeningState
  ]

  @type t :: %__MODULE__{
          :detailsType => String.t(),
          :dateTimeModification => DateTime.t(),
          :caseScreeningState => ExWorldCheck.Model.CaseScreeningState.t()
        }

  alias ExWorldCheck.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :caseScreeningState,
      :struct,
      ExWorldCheck.Model.CaseScreeningState
    )
  end
end
