# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.ChangeCaseScreeningStateAuditDetails do
  @moduledoc """
  Audit details for CHANGE_CASE_SCREENING_STATE action raised when the Case Screening state has changed. Extends [AbstractAuditDetails](#AbstractAuditDetails).
  """

  @derive [Poison.Encoder]
  defstruct [
    :detailsType,
    :dateTimeModification,
    :caseScreeningState
  ]

  @type t :: %__MODULE__{
          :detailsType => String.t(),
          :dateTimeModification => DateTime.t(),
          :caseScreeningState => ExWorldCheck.Model.CaseScreeningState.t()
        }
end

defimpl Poison.Decoder, for: ExWorldCheck.Model.ChangeCaseScreeningStateAuditDetails do
  import ExWorldCheck.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:caseScreeningState, :struct, ExWorldCheck.Model.CaseScreeningState, options)
  end
end
