# NOTE: This file is auto generated by OpenAPI Generator 7.13.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.ChangeCaseLifecycleStateAuditDetails do
  @moduledoc """
  Audit details for CHANGE_CASE_LIFECYCLE_STATE action raised when the Case Lifecycle state has changed. Extends [AbstractAuditDetails](#AbstractAuditDetails).
  """

  @derive JSON.Encoder
  defstruct [
    :detailsType,
    :previousCaseLifecycleState,
    :nextCaseLifecycleState
  ]

  @type t :: %__MODULE__{
          :detailsType => String.t(),
          :previousCaseLifecycleState => String.t(),
          :nextCaseLifecycleState => String.t()
        }

  def decode(value) do
    value
  end
end
