# NOTE: This file is auto generated by OpenAPI Generator 7.13.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.ChangedCaseMediaCheckSmartFilterPreferenceAuditDetails do
  @moduledoc """
  Audit details which contains details of changing the state of MediaCheck smart filter. Extends [AbstractAuditDetails](#AbstractAuditDetails).
  """

  @derive JSON.Encoder
  defstruct [
    :detailsType,
    :casePreferenceType,
    :status,
    :dateTimeModification
  ]

  @type t :: %__MODULE__{
          :detailsType => String.t(),
          :casePreferenceType => ExWorldCheck.Model.CasePreferenceType.t(),
          :status => String.t(),
          :dateTimeModification => DateTime.t()
        }

  alias ExWorldCheck.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :casePreferenceType,
      :struct,
      ExWorldCheck.Model.CasePreferenceType
    )
  end
end
