# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.ChangedCaseMediaCheckOgsPreferenceAuditDetailsAllOf do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :casePreferenceType,
    :status,
    :dateTimeModification
  ]

  @type t :: %__MODULE__{
          :casePreferenceType => ExWorldCheck.Model.CasePreferenceType.t(),
          :status => String.t(),
          :dateTimeModification => DateTime.t()
        }
end

defimpl Poison.Decoder,
  for: ExWorldCheck.Model.ChangedCaseMediaCheckOgsPreferenceAuditDetailsAllOf do
  import ExWorldCheck.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:casePreferenceType, :struct, ExWorldCheck.Model.CasePreferenceType, options)
  end
end
