# NOTE: This file is auto generated by OpenAPI Generator 7.13.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.ChildCaseMove do
  @moduledoc """
  Audit details which contains information about the childcase. Extends [AbstractAuditDetails](#AbstractAuditDetails).
  """

  @derive JSON.Encoder
  defstruct [
    :detailsType,
    :fromParentCaseExternalId,
    :toParentCaseExternalId
  ]

  @type t :: %__MODULE__{
          :detailsType => String.t(),
          :fromParentCaseExternalId => String.t(),
          :toParentCaseExternalId => String.t()
        }

  def decode(value) do
    value
  end
end
