# NOTE: This file is auto generated by OpenAPI Generator 7.13.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.ChildCaseEventAuditDetails do
  @moduledoc """
  Audit details contain information about a child case. For example, an audit event when the user creates a new child case under an existing parent or one or more child cases are deleted. Extends [AbstractAuditDetails](#AbstractAuditDetails). 
  """

  @derive JSON.Encoder
  defstruct [
    :detailsType,
    :childCaseExternalId
  ]

  @type t :: %__MODULE__{
          :detailsType => String.t(),
          :childCaseExternalId => String.t()
        }

  def decode(value) do
    value
  end
end
