# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.ChildCaseMove do
  @moduledoc """
  Audit details which contains information about the childcase. Extends [AbstractAuditDetails](#AbstractAuditDetails).
  """

  @derive [Poison.Encoder]
  defstruct [
    :detailsType,
    :fromParentCaseExternalId,
    :toParentCaseExternalId
  ]

  @type t :: %__MODULE__{
          :detailsType => String.t(),
          :fromParentCaseExternalId => String.t(),
          :toParentCaseExternalId => String.t()
        }
end

defimpl Poison.Decoder, for: ExWorldCheck.Model.ChildCaseMove do
  def decode(value, _options) do
    value
  end
end
