# NOTE: This file is auto generated by OpenAPI Generator 7.13.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.ChildCaseTransferredOutParent do
  @moduledoc """
  Audit details contain information about a child case. For example, an audit event when a user moves a child case from/to one parent to another. Extends [AbstractAuditDetails](#AbstractAuditDetails). 
  """

  @derive JSON.Encoder
  defstruct [
    :detailsType,
    :childCaseExternalId,
    :toParentCaseExternalId
  ]

  @type t :: %__MODULE__{
          :detailsType => String.t(),
          :childCaseExternalId => String.t(),
          :toParentCaseExternalId => String.t()
        }

  def decode(value) do
    value
  end
end
