# NOTE: This file is auto generated by OpenAPI Generator 7.13.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.ChildCaseTransferredInParent do
  @moduledoc """
  Audit details which contains information about a child case. Extends [AbstractAuditDetails](#AbstractAuditDetails).
  """

  @derive JSON.Encoder
  defstruct [
    :detailsType,
    :childCaseExternalId,
    :fromParentCaseExternalId
  ]

  @type t :: %__MODULE__{
          :detailsType => String.t(),
          :childCaseExternalId => String.t(),
          :fromParentCaseExternalId => String.t()
        }

  def decode(value) do
    value
  end
end
