# NOTE: This file is auto generated by OpenAPI Generator 7.13.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.ContactDetail do
  @moduledoc """

  """

  @derive JSON.Encoder
  defstruct [
    :contactDetailType,
    :country,
    :detail
  ]

  @type t :: %__MODULE__{
          :contactDetailType => String.t(),
          :country => ExWorldCheck.Model.Country.t() | nil,
          :detail => String.t() | nil
        }

  alias ExWorldCheck.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:country, :struct, ExWorldCheck.Model.Country)
  end
end
