# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.CountryLink do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :country,
    :countryText,
    :type
  ]

  @type t :: %__MODULE__{
          :country => ExWorldCheck.Model.Country.t(),
          :countryText => String.t() | nil,
          :type => String.t()
        }
end

defimpl Poison.Decoder, for: ExWorldCheck.Model.CountryLink do
  import ExWorldCheck.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:country, :struct, ExWorldCheck.Model.Country, options)
  end
end
