# NOTE: This file is auto generated by OpenAPI Generator 7.13.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.CountryLink do
  @moduledoc """

  """

  @derive JSON.Encoder
  defstruct [
    :country,
    :countryText,
    :type
  ]

  @type t :: %__MODULE__{
          :country => ExWorldCheck.Model.Country.t(),
          :countryText => String.t() | nil,
          :type => String.t()
        }

  alias ExWorldCheck.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:country, :struct, ExWorldCheck.Model.Country)
  end
end
