# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.CursorOptions do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :itemsPerPage
  ]

  @type t :: %__MODULE__{
          :itemsPerPage => integer() | nil
        }
end

defimpl Poison.Decoder, for: ExWorldCheck.Model.CursorOptions do
  def decode(value, _options) do
    value
  end
end
