# NOTE: This file is auto generated by OpenAPI Generator 7.13.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.Cursor do
  @moduledoc """
  Identifier which allows retrieving next N cases.
  """

  @derive JSON.Encoder
  defstruct [
    :cursorId
  ]

  @type t :: %__MODULE__{
          :cursorId => String.t()
        }

  def decode(value) do
    value
  end
end
