# NOTE: This file is auto generated by OpenAPI Generator 7.13.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.CursorOptions do
  @moduledoc """

  """

  @derive JSON.Encoder
  defstruct [
    :itemsPerPage
  ]

  @type t :: %__MODULE__{
          :itemsPerPage => integer() | nil
        }

  def decode(value) do
    value
  end
end
