# NOTE: This file is auto generated by OpenAPI Generator 7.13.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.Detail do
  @moduledoc """

  """

  @derive JSON.Encoder
  defstruct [
    :detailType,
    :text,
    :title
  ]

  @type t :: %__MODULE__{
          :detailType => String.t() | nil,
          :text => String.t() | nil,
          :title => String.t() | nil
        }

  def decode(value) do
    value
  end
end
