# NOTE: This file is auto generated by OpenAPI Generator 7.13.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.EntityPurge do
  @moduledoc """

  """

  @derive JSON.Encoder
  defstruct [
    :entityId,
    :purgedDate
  ]

  @type t :: %__MODULE__{
          :entityId => String.t(),
          :purgedDate => DateTime.t() | nil
        }

  def decode(value) do
    value
  end
end
