# NOTE: This file is auto generated by OpenAPI Generator 7.13.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.EntityDelete do
  @moduledoc """

  """

  @derive JSON.Encoder
  defstruct [
    :entityId
  ]

  @type t :: %__MODULE__{
          :entityId => String.t()
        }

  def decode(value) do
    value
  end
end
