# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.EntityDelete do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :entityId
  ]

  @type t :: %__MODULE__{
          :entityId => String.t()
        }
end

defimpl Poison.Decoder, for: ExWorldCheck.Model.EntityDelete do
  def decode(value, _options) do
    value
  end
end
