# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.Entity do
  @moduledoc """
  Represents a specific entity - usually corresponding to an individual or an organisation - that can appear as a potential screening result against a `Case`. Synonyms for this concept include \"Profile\".  The `Entity` subclasses corresponding to each type of entity (designated by the `entityType` field below) are:  * `COUNTRY` : `CountryEntity` * `INDIVIDUAL` : `IndividualEntity` * `ORGANISATION` : `OrganisationEntity` * `VESSEL` : `VesselEntity`  Notes for Client Watchlist usage:  * to add Date of Birth to an Individual entity, please use the `events` array with the \"type\":\"BIRTH\" * to add Place of Birth to an Individual entity, please use the `events` array with the \"type\":\"BIRTH\" and populate the `Region` field as part of the event `address` object * to add Registered Country to a Vessel entity, please use  the `countryLinks` array with the \"type\":\"VESSELFLAG\" * to add Registered Country to an Organisation entity, please use the `countryLinks` array with the \"type\": \"REGISTEREDIN\" 
  """

  @derive [Poison.Encoder]
  defstruct [
    :actions,
    :active,
    :addresses,
    :associates,
    :category,
    :comments,
    :contacts,
    :countryLinks,
    :creationDate,
    :deletionDate,
    :description,
    :details,
    :entityId,
    :externalImportId,
    :files,
    :identityDocuments,
    :images,
    :lastAdjunctChangeDate,
    :modificationDate,
    :names,
    :previousCountryLinks,
    :provider,
    :sourceDescription,
    :sourceUris,
    :sources,
    :subCategory,
    :updateCategory,
    :updatedDates,
    :weblinks
  ]

  @type t :: %__MODULE__{
          :actions => [ExWorldCheck.Model.ActionDetail.t()] | nil,
          :active => boolean() | nil,
          :addresses => [ExWorldCheck.Model.Address.t()] | nil,
          :associates => [ExWorldCheck.Model.AbstractAssociate.t()] | nil,
          :category => String.t() | nil,
          :comments => String.t() | nil,
          :contacts => [ExWorldCheck.Model.ContactDetail.t()] | nil,
          :countryLinks => [ExWorldCheck.Model.CountryLink.t()] | nil,
          :creationDate => DateTime.t(),
          :deletionDate => DateTime.t() | nil,
          :description => String.t() | nil,
          :details => [ExWorldCheck.Model.Detail.t()] | nil,
          :entityId => String.t(),
          :externalImportId => String.t(),
          :files => [ExWorldCheck.Model.FileMeta.t()] | nil,
          :identityDocuments => [ExWorldCheck.Model.IdentityDocument.t()] | nil,
          :images => [ExWorldCheck.Model.Image.t()] | nil,
          :lastAdjunctChangeDate => DateTime.t() | nil,
          :modificationDate => DateTime.t() | nil,
          :names => [ExWorldCheck.Model.Name.t()],
          :previousCountryLinks => [ExWorldCheck.Model.CountryLink.t()] | nil,
          :provider => ExWorldCheck.Model.Provider.t() | nil,
          :sourceDescription => String.t() | nil,
          :sourceUris => [String.t()] | nil,
          :sources => [ExWorldCheck.Model.ProviderSource.t()],
          :subCategory => String.t() | nil,
          :updateCategory => String.t() | nil,
          :updatedDates => ExWorldCheck.Model.EntityUpdatedDates.t() | nil,
          :weblinks => [ExWorldCheck.Model.Weblink.t()] | nil
        }
end

defimpl Poison.Decoder, for: ExWorldCheck.Model.Entity do
  import ExWorldCheck.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:actions, :list, ExWorldCheck.Model.ActionDetail, options)
    |> deserialize(:addresses, :list, ExWorldCheck.Model.Address, options)
    |> deserialize(:associates, :list, ExWorldCheck.Model.AbstractAssociate, options)
    |> deserialize(:contacts, :list, ExWorldCheck.Model.ContactDetail, options)
    |> deserialize(:countryLinks, :list, ExWorldCheck.Model.CountryLink, options)
    |> deserialize(:details, :list, ExWorldCheck.Model.Detail, options)
    |> deserialize(:files, :list, ExWorldCheck.Model.FileMeta, options)
    |> deserialize(:identityDocuments, :list, ExWorldCheck.Model.IdentityDocument, options)
    |> deserialize(:images, :list, ExWorldCheck.Model.Image, options)
    |> deserialize(:names, :list, ExWorldCheck.Model.Name, options)
    |> deserialize(:previousCountryLinks, :list, ExWorldCheck.Model.CountryLink, options)
    |> deserialize(:provider, :struct, ExWorldCheck.Model.Provider, options)
    |> deserialize(:sources, :list, ExWorldCheck.Model.ProviderSource, options)
    |> deserialize(:updatedDates, :struct, ExWorldCheck.Model.EntityUpdatedDates, options)
    |> deserialize(:weblinks, :list, ExWorldCheck.Model.Weblink, options)
  end
end
