# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.EntityPurge do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :entityId,
    :purgedDate
  ]

  @type t :: %__MODULE__{
          :entityId => String.t(),
          :purgedDate => DateTime.t() | nil
        }
end

defimpl Poison.Decoder, for: ExWorldCheck.Model.EntityPurge do
  def decode(value, _options) do
    value
  end
end
