# NOTE: This file is auto generated by OpenAPI Generator 7.13.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.Error do
  @moduledoc """

  """

  @derive JSON.Encoder
  defstruct [
    :error,
    :cause,
    :objectId
  ]

  @type t :: %__MODULE__{
          :error => String.t(),
          :cause => String.t(),
          :objectId => String.t() | nil
        }

  def decode(value) do
    value
  end
end
