# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.Error do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :error,
    :cause,
    :objectId
  ]

  @type t :: %__MODULE__{
          :error => String.t(),
          :cause => String.t(),
          :objectId => String.t() | nil
        }
end

defimpl Poison.Decoder, for: ExWorldCheck.Model.Error do
  def decode(value, _options) do
    value
  end
end
