# NOTE: This file is auto generated by OpenAPI Generator 7.13.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.Event do
  @moduledoc """

  """

  @derive JSON.Encoder
  defstruct [
    :address,
    :allegedAddresses,
    :day,
    :fullDate,
    :month,
    :type,
    :year
  ]

  @type t :: %__MODULE__{
          :address => ExWorldCheck.Model.Address.t() | nil,
          :allegedAddresses => [ExWorldCheck.Model.Address.t()] | nil,
          :day => integer() | nil,
          :fullDate => String.t() | nil,
          :month => integer() | nil,
          :type => ExWorldCheck.Model.EventType.t(),
          :year => integer() | nil
        }

  alias ExWorldCheck.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:address, :struct, ExWorldCheck.Model.Address)
    |> Deserializer.deserialize(:allegedAddresses, :list, ExWorldCheck.Model.Address)
    |> Deserializer.deserialize(:type, :struct, ExWorldCheck.Model.EventType)
  end
end
