# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.Event do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :address,
    :allegedAddresses,
    :day,
    :fullDate,
    :month,
    :type,
    :year
  ]

  @type t :: %__MODULE__{
          :address => ExWorldCheck.Model.Address.t() | nil,
          :allegedAddresses => [ExWorldCheck.Model.Address.t()] | nil,
          :day => integer() | nil,
          :fullDate => String.t() | nil,
          :month => integer() | nil,
          :type => ExWorldCheck.Model.EventType.t(),
          :year => integer() | nil
        }
end

defimpl Poison.Decoder, for: ExWorldCheck.Model.Event do
  import ExWorldCheck.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:address, :struct, ExWorldCheck.Model.Address, options)
    |> deserialize(:allegedAddresses, :list, ExWorldCheck.Model.Address, options)
    |> deserialize(:type, :struct, ExWorldCheck.Model.EventType, options)
  end
end
