# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.FieldAllOf do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :value,
    :dateTimeValue
  ]

  @type t :: %__MODULE__{
          :value => String.t() | nil,
          :dateTimeValue => DateTime.t() | nil
        }
end

defimpl Poison.Decoder, for: ExWorldCheck.Model.FieldAllOf do
  def decode(value, _options) do
    value
  end
end
