# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.FieldDefinition do
  @moduledoc """
  Secondary or Custom Field metadata describing the rules for populating the corresponding Field data when creating or updating a Case. Extends [AbstractField](#AbstractField). 
  """

  @derive [Poison.Encoder]
  defstruct [
    :typeId,
    :fieldValueType,
    :fieldRequired,
    :label,
    :regExp
  ]

  @type t :: %__MODULE__{
          :typeId => String.t(),
          :fieldValueType => ExWorldCheck.Model.FieldValueType.t(),
          :fieldRequired => boolean() | nil,
          :label => String.t(),
          :regExp => String.t() | nil
        }
end

defimpl Poison.Decoder, for: ExWorldCheck.Model.FieldDefinition do
  import ExWorldCheck.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:fieldValueType, :struct, ExWorldCheck.Model.FieldValueType, options)
  end
end
