# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.FieldDefinitionAllOf do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :fieldValueType,
    :fieldRequired,
    :label,
    :regExp
  ]

  @type t :: %__MODULE__{
          :fieldValueType => ExWorldCheck.Model.FieldValueType.t(),
          :fieldRequired => boolean() | nil,
          :label => String.t(),
          :regExp => String.t() | nil
        }
end

defimpl Poison.Decoder, for: ExWorldCheck.Model.FieldDefinitionAllOf do
  import ExWorldCheck.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:fieldValueType, :struct, ExWorldCheck.Model.FieldValueType, options)
  end
end
