# NOTE: This file is auto generated by OpenAPI Generator 7.13.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.Filter do
  @moduledoc """
  Filter the response
  """

  @derive JSON.Encoder
  defstruct [
    :query,
    :sort,
    :pagination
  ]

  @type t :: %__MODULE__{
          :query => String.t() | nil,
          :sort => [ExWorldCheck.Model.SortCriterion.t()] | nil,
          :pagination => ExWorldCheck.Model.Pagination.t() | nil
        }

  alias ExWorldCheck.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:sort, :list, ExWorldCheck.Model.SortCriterion)
    |> Deserializer.deserialize(:pagination, :struct, ExWorldCheck.Model.Pagination)
  end
end
