# NOTE: This file is auto generated by OpenAPI Generator 7.13.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.Group do
  @moduledoc """
  Structure of Groups accessible by user
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :parentId,
    :name,
    :hasChildren,
    :children,
    :status
  ]

  @type t :: %__MODULE__{
          :id => String.t(),
          :parentId => String.t() | nil,
          :name => String.t(),
          :hasChildren => boolean() | nil,
          :children => [ExWorldCheck.Model.Group.t()] | nil,
          :status => ExWorldCheck.Model.StatusType.t() | nil
        }

  alias ExWorldCheck.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:children, :list, ExWorldCheck.Model.Group)
    |> Deserializer.deserialize(:status, :struct, ExWorldCheck.Model.StatusType)
  end
end
