# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.Group do
  @moduledoc """
  Structure of Groups accessible by user
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :parentId,
    :name,
    :hasChildren,
    :children,
    :status
  ]

  @type t :: %__MODULE__{
          :id => String.t(),
          :parentId => String.t() | nil,
          :name => String.t(),
          :hasChildren => boolean() | nil,
          :children => [ExWorldCheck.Model.Group.t()] | nil,
          :status => ExWorldCheck.Model.StatusType.t() | nil
        }
end

defimpl Poison.Decoder, for: ExWorldCheck.Model.Group do
  import ExWorldCheck.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:children, :list, ExWorldCheck.Model.Group, options)
    |> deserialize(:status, :struct, ExWorldCheck.Model.StatusType, options)
  end
end
