# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.IdentityDocument do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :entity,
    :expiryDate,
    :issueDate,
    :issuer,
    :locationType,
    :number,
    :type
  ]

  @type t :: %__MODULE__{
          :entity => ExWorldCheck.Model.Entity.t() | nil,
          :expiryDate => String.t() | nil,
          :issueDate => String.t() | nil,
          :issuer => String.t() | nil,
          :locationType => ExWorldCheck.Model.IdentityDocumentLocationType.t() | nil,
          :number => String.t() | nil,
          :type => String.t() | nil
        }
end

defimpl Poison.Decoder, for: ExWorldCheck.Model.IdentityDocument do
  import ExWorldCheck.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:entity, :struct, ExWorldCheck.Model.Entity, options)
    |> deserialize(
      :locationType,
      :struct,
      ExWorldCheck.Model.IdentityDocumentLocationType,
      options
    )
  end
end
