# NOTE: This file is auto generated by OpenAPI Generator 7.13.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.IdentityDocumentLocationType do
  @moduledoc """
  Represents the type of identity document location that includes the type of document, name, country, and what type of entity it belongs to. 
  """

  @derive JSON.Encoder
  defstruct [
    :country,
    :name,
    :type,
    :entityTypes
  ]

  @type t :: %__MODULE__{
          :country => ExWorldCheck.Model.Country.t() | nil,
          :name => String.t() | nil,
          :type => String.t() | nil,
          :entityTypes => [ExWorldCheck.Model.EntityType.t()] | nil
        }

  alias ExWorldCheck.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:country, :struct, ExWorldCheck.Model.Country)
    |> Deserializer.deserialize(:entityTypes, :list, ExWorldCheck.Model.EntityType)
  end
end
