# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.IdentityDocumentLocationTypeDataSet do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :identityDocumentLocationTypes
  ]

  @type t :: %__MODULE__{
          :identityDocumentLocationTypes =>
            [ExWorldCheck.Model.IdentityDocumentLocationType.t()] | nil
        }
end

defimpl Poison.Decoder, for: ExWorldCheck.Model.IdentityDocumentLocationTypeDataSet do
  import ExWorldCheck.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :identityDocumentLocationTypes,
      :list,
      ExWorldCheck.Model.IdentityDocumentLocationType,
      options
    )
  end
end
