# NOTE: This file is auto generated by OpenAPI Generator 7.13.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.Image do
  @moduledoc """

  """

  @derive JSON.Encoder
  defstruct [
    :caption,
    :height,
    :imageUseCode,
    :uri,
    :tags,
    :width
  ]

  @type t :: %__MODULE__{
          :caption => String.t() | nil,
          :height => integer() | nil,
          :imageUseCode => String.t() | nil,
          :uri => String.t(),
          :tags => [String.t()] | nil,
          :width => integer() | nil
        }

  def decode(value) do
    value
  end
end
