# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.IndividualEntityAllOf do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :age,
    :ageAsOfDate,
    :events,
    :gender,
    :isDeceased,
    :previousRoles,
    :roles,
    :entityType
  ]

  @type t :: %__MODULE__{
          :age => String.t() | nil,
          :ageAsOfDate => DateTime.t() | nil,
          :events => [ExWorldCheck.Model.Event.t()] | nil,
          :gender => ExWorldCheck.Model.Gender.t() | nil,
          :isDeceased => boolean() | nil,
          :previousRoles => [ExWorldCheck.Model.Role.t()] | nil,
          :roles => [ExWorldCheck.Model.Role.t()] | nil,
          :entityType => String.t() | nil
        }
end

defimpl Poison.Decoder, for: ExWorldCheck.Model.IndividualEntityAllOf do
  import ExWorldCheck.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:events, :list, ExWorldCheck.Model.Event, options)
    |> deserialize(:gender, :struct, ExWorldCheck.Model.Gender, options)
    |> deserialize(:previousRoles, :list, ExWorldCheck.Model.Role, options)
    |> deserialize(:roles, :list, ExWorldCheck.Model.Role, options)
  end
end
