# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.LinkedCasesRequest do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :relatedCaseSystemIds,
    :note
  ]

  @type t :: %__MODULE__{
          :relatedCaseSystemIds => [String.t()],
          :note => String.t() | nil
        }
end

defimpl Poison.Decoder, for: ExWorldCheck.Model.LinkedCasesRequest do
  def decode(value, _options) do
    value
  end
end
