# NOTE: This file is auto generated by OpenAPI Generator 7.13.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.MatchedTerm do
  @moduledoc """
  Matched term of a Result.
  """

  @derive JSON.Encoder
  defstruct [
    :term,
    :type
  ]

  @type t :: %__MODULE__{
          :term => String.t() | nil,
          :type => String.t() | nil
        }

  def decode(value) do
    value
  end
end
