# NOTE: This file is auto generated by OpenAPI Generator 7.13.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.MediaCheckPublicationDetails do
  @moduledoc """
  News article publisher details.
  """

  @derive JSON.Encoder
  defstruct [
    :code,
    :countries,
    :description,
    :languages,
    :name,
    :publicationTypes,
    :regions,
    :sectors,
    :status
  ]

  @type t :: %__MODULE__{
          :code => String.t() | nil,
          :countries => [String.t()] | nil,
          :description => String.t() | nil,
          :languages => [String.t()] | nil,
          :name => String.t() | nil,
          :publicationTypes => [String.t()] | nil,
          :regions => [String.t()] | nil,
          :sectors => [String.t()] | nil,
          :status => String.t() | nil
        }

  def decode(value) do
    value
  end
end
