# NOTE: This file is auto generated by OpenAPI Generator 7.13.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.MediaCheckCaseDetails do
  @moduledoc """
  Details about the Media-Check settings on a case (e.g., smart filter).
  """

  @derive JSON.Encoder
  defstruct [
    :smartFilter
  ]

  @type t :: %__MODULE__{
          :smartFilter => boolean()
        }

  def decode(value) do
    value
  end
end
