# NOTE: This file is auto generated by OpenAPI Generator 7.13.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.MediaCheckDetachArticlesRequest do
  @moduledoc """
  Articles to detach.
  """

  @derive JSON.Encoder
  defstruct [
    :articleIds
  ]

  @type t :: %__MODULE__{
          :articleIds => [String.t()]
        }

  def decode(value) do
    value
  end
end
