# NOTE: This file is auto generated by OpenAPI Generator 7.13.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.MediaCheckArticlesMetadataResponse do
  @moduledoc """

  """

  @derive JSON.Encoder
  defstruct [
    :results
  ]

  @type t :: %__MODULE__{
          :results => [ExWorldCheck.Model.MediaCheckResult.t()] | nil
        }

  alias ExWorldCheck.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:results, :list, ExWorldCheck.Model.MediaCheckResult)
  end
end
