# NOTE: This file is auto generated by OpenAPI Generator 7.13.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.MediaCheckDuplicatesRequest do
  @moduledoc """
  Request containing deduplication hash to retrieve article duplicatates.
  """

  @derive JSON.Encoder
  defstruct [
    :deduplicationHash
  ]

  @type t :: %__MODULE__{
          :deduplicationHash => String.t() | nil
        }

  def decode(value) do
    value
  end
end
