# NOTE: This file is auto generated by OpenAPI Generator 7.13.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.MediaCheckRegularFacetResponse do
  @moduledoc """

  """

  @derive JSON.Encoder
  defstruct [
    :drilldownKey,
    :facetLabel,
    :articleCount
  ]

  @type t :: %__MODULE__{
          :drilldownKey => String.t() | nil,
          :facetLabel => String.t() | nil,
          :articleCount => integer() | nil
        }

  def decode(value) do
    value
  end
end
