# NOTE: This file is auto generated by OpenAPI Generator 7.13.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.MediaCheckArticleContent do
  @moduledoc """
  MediaCheck news article content
  """

  @derive JSON.Encoder
  defstruct [
    :content,
    :copyrightHolder,
    :copyrightNotice
  ]

  @type t :: %__MODULE__{
          :content => String.t() | nil,
          :copyrightHolder => String.t() | nil,
          :copyrightNotice => String.t() | nil
        }

  def decode(value) do
    value
  end
end
