# NOTE: This file is auto generated by OpenAPI Generator 7.13.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.MediaCheckPublicationDateRange do
  @moduledoc """
  Date range when the article was published.
  """

  @derive JSON.Encoder
  defstruct [
    :min,
    :max
  ]

  @type t :: %__MODULE__{
          :min => DateTime.t() | nil,
          :max => DateTime.t() | nil
        }

  def decode(value) do
    value
  end
end
