# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.MediaCheckBaseFilter do
  @moduledoc """
  Used to filter news search results.
  """

  @derive [Poison.Encoder]
  defstruct [
    :publicationDate,
    :query,
    :archivedArticles,
    :reviewRequiredArticles,
    :smartFilter,
    :deduplicatedArticles
  ]

  @type t :: %__MODULE__{
          :publicationDate => ExWorldCheck.Model.MediaCheckPublicationDateRange.t() | nil,
          :query => String.t() | nil,
          :archivedArticles => boolean() | nil,
          :reviewRequiredArticles => boolean() | nil,
          :smartFilter => boolean() | nil,
          :deduplicatedArticles => String.t() | nil
        }
end

defimpl Poison.Decoder, for: ExWorldCheck.Model.MediaCheckBaseFilter do
  import ExWorldCheck.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :publicationDate,
      :struct,
      ExWorldCheck.Model.MediaCheckPublicationDateRange,
      options
    )
  end
end
