# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.MediaCheckPublicationDatesFacetResponse do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :drilldownKey,
    :facetLabel,
    :articleCount,
    :selectedCount
  ]

  @type t :: %__MODULE__{
          :drilldownKey => String.t() | nil,
          :facetLabel => String.t() | nil,
          :articleCount => integer() | nil,
          :selectedCount => integer() | nil
        }
end

defimpl Poison.Decoder, for: ExWorldCheck.Model.MediaCheckPublicationDatesFacetResponse do
  def decode(value, _options) do
    value
  end
end
