# NOTE: This file is auto generated by OpenAPI Generator 7.13.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.MediaCheckFacetsResponse do
  @moduledoc """
  Facets for article navigation. Use facet's `drilldownKey` to select a facet
  """

  @derive JSON.Encoder
  defstruct [
    :publicationTypes,
    :geographies,
    :topics,
    :topicPhases,
    :countries,
    :publicationDates
  ]

  @type t :: %__MODULE__{
          :publicationTypes => [ExWorldCheck.Model.MediaCheckRegularFacetResponse.t()] | nil,
          :geographies => [[ExWorldCheck.Model.MediaCheckRegularFacetResponse.t()]] | nil,
          :topics => [ExWorldCheck.Model.MediaCheckRegularFacetResponse.t()] | nil,
          :topicPhases => [ExWorldCheck.Model.MediaCheckRegularFacetResponse.t()] | nil,
          :countries => [ExWorldCheck.Model.MediaCheckRegularFacetResponse.t()] | nil,
          :publicationDates =>
            [ExWorldCheck.Model.MediaCheckPublicationDatesFacetResponse.t()] | nil
        }

  alias ExWorldCheck.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :publicationTypes,
      :list,
      ExWorldCheck.Model.MediaCheckRegularFacetResponse
    )
    |> Deserializer.deserialize(:topics, :list, ExWorldCheck.Model.MediaCheckRegularFacetResponse)
    |> Deserializer.deserialize(
      :topicPhases,
      :list,
      ExWorldCheck.Model.MediaCheckRegularFacetResponse
    )
    |> Deserializer.deserialize(
      :countries,
      :list,
      ExWorldCheck.Model.MediaCheckRegularFacetResponse
    )
    |> Deserializer.deserialize(
      :publicationDates,
      :list,
      ExWorldCheck.Model.MediaCheckPublicationDatesFacetResponse
    )
  end
end
