# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.MediaCheckArticlesMetadataRequest do
  @moduledoc """
  Definition of MediaCheck news articles content request
  """

  @derive [Poison.Encoder]
  defstruct [
    :articleIds
  ]

  @type t :: %__MODULE__{
          :articleIds => [String.t()]
        }
end

defimpl Poison.Decoder, for: ExWorldCheck.Model.MediaCheckArticlesMetadataRequest do
  def decode(value, _options) do
    value
  end
end
