# NOTE: This file is auto generated by OpenAPI Generator 7.13.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.MediaCheckFacetsRequest do
  @moduledoc """
  Facets for MediaCheckResultsRequest
  """

  @derive JSON.Encoder
  defstruct [
    :publicationType,
    :topicPhase,
    :geography,
    :topic,
    :country,
    :publicationDate
  ]

  @type t :: %__MODULE__{
          :publicationType => ExWorldCheck.Model.MediaCheckRegularFacetRequest.t() | nil,
          :topicPhase => ExWorldCheck.Model.MediaCheckRegularFacetRequest.t() | nil,
          :geography => ExWorldCheck.Model.MediaCheckRegularFacetRequest.t() | nil,
          :topic => ExWorldCheck.Model.MediaCheckRegularFacetRequest.t() | nil,
          :country => ExWorldCheck.Model.MediaCheckRegularFacetRequest.t() | nil,
          :publicationDate => map() | nil
        }

  alias ExWorldCheck.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :publicationType,
      :struct,
      ExWorldCheck.Model.MediaCheckRegularFacetRequest
    )
    |> Deserializer.deserialize(
      :topicPhase,
      :struct,
      ExWorldCheck.Model.MediaCheckRegularFacetRequest
    )
    |> Deserializer.deserialize(
      :geography,
      :struct,
      ExWorldCheck.Model.MediaCheckRegularFacetRequest
    )
    |> Deserializer.deserialize(:topic, :struct, ExWorldCheck.Model.MediaCheckRegularFacetRequest)
    |> Deserializer.deserialize(
      :country,
      :struct,
      ExWorldCheck.Model.MediaCheckRegularFacetRequest
    )
  end
end
