# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.MediaCheckArticlesMetadataResponse do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :results
  ]

  @type t :: %__MODULE__{
          :results => [ExWorldCheck.Model.MediaCheckResult.t()] | nil
        }
end

defimpl Poison.Decoder, for: ExWorldCheck.Model.MediaCheckArticlesMetadataResponse do
  import ExWorldCheck.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:results, :list, ExWorldCheck.Model.MediaCheckResult, options)
  end
end
