# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.MediaCheckDuplicatesRequest do
  @moduledoc """
  Request containing deduplication hash to retrieve article duplicatates.
  """

  @derive [Poison.Encoder]
  defstruct [
    :deduplicationHash
  ]

  @type t :: %__MODULE__{
          :deduplicationHash => String.t() | nil
        }
end

defimpl Poison.Decoder, for: ExWorldCheck.Model.MediaCheckDuplicatesRequest do
  def decode(value, _options) do
    value
  end
end
