# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.MediaCheckRegularFacetRequest do
  @moduledoc """
  Facets for MediaCheckResultsRequest
  """

  @derive [Poison.Encoder]
  defstruct [
    :limit
  ]

  @type t :: %__MODULE__{
          :limit => integer() | nil
        }
end

defimpl Poison.Decoder, for: ExWorldCheck.Model.MediaCheckRegularFacetRequest do
  def decode(value, _options) do
    value
  end
end
