# NOTE: This file is auto generated by OpenAPI Generator 7.13.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.MediaCheckBaseFilter do
  @moduledoc """
  Used to filter news search results.
  """

  @derive JSON.Encoder
  defstruct [
    :publicationDate,
    :query,
    :archivedArticles,
    :reviewRequiredArticles,
    :smartFilter,
    :deduplicatedArticles
  ]

  @type t :: %__MODULE__{
          :publicationDate => ExWorldCheck.Model.MediaCheckPublicationDateRange.t() | nil,
          :query => String.t() | nil,
          :archivedArticles => boolean() | nil,
          :reviewRequiredArticles => boolean() | nil,
          :smartFilter => boolean() | nil,
          :deduplicatedArticles => String.t() | nil
        }

  alias ExWorldCheck.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :publicationDate,
      :struct,
      ExWorldCheck.Model.MediaCheckPublicationDateRange
    )
  end
end
