# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.MigrationEventAuditDetails do
  @moduledoc """
  Audit details for MIGRATION action raised when migration of names is performed. Extends [AbstractAuditDetails](#AbstractAuditDetails).
  """

  @derive [Poison.Encoder]
  defstruct [
    :detailsType,
    :caseSystemId,
    :actionLogs
  ]

  @type t :: %__MODULE__{
          :detailsType => String.t(),
          :caseSystemId => String.t() | nil,
          :actionLogs => [ExWorldCheck.Model.AbstractMigrationEventPayload.t()] | nil
        }
end

defimpl Poison.Decoder, for: ExWorldCheck.Model.MigrationEventAuditDetails do
  import ExWorldCheck.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:actionLogs, :list, ExWorldCheck.Model.AbstractMigrationEventPayload, options)
  end
end
