# NOTE: This file is auto generated by OpenAPI Generator 7.13.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.MigrationEventAuditDetails do
  @moduledoc """
  Audit details for MIGRATION action raised when migration of names is performed. Extends [AbstractAuditDetails](#AbstractAuditDetails).
  """

  @derive JSON.Encoder
  defstruct [
    :detailsType,
    :caseSystemId,
    :actionLogs
  ]

  @type t :: %__MODULE__{
          :detailsType => String.t(),
          :caseSystemId => String.t() | nil,
          :actionLogs => [ExWorldCheck.Model.AbstractMigrationEventPayload.t()] | nil
        }

  alias ExWorldCheck.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :actionLogs,
      :list,
      ExWorldCheck.Model.AbstractMigrationEventPayload
    )
  end
end
