# NOTE: This file is auto generated by OpenAPI Generator 7.13.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.MrzGenerationResponse do
  @moduledoc """
  PassportCheck Machine Readable Zone (MRZ) data response 
  """

  @derive JSON.Encoder
  defstruct [
    :lines,
    :isConformICAO
  ]

  @type t :: %__MODULE__{
          :lines => [String.t()] | nil,
          :isConformICAO => boolean() | nil
        }

  def decode(value) do
    value
  end
end
