# NOTE: This file is auto generated by OpenAPI Generator 7.13.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.MrzGenerationRequest do
  @moduledoc """
  PassportCheck Machine Readable Zone (MRZ) data request 
  """

  @derive JSON.Encoder
  defstruct [
    :givenName,
    :lastName,
    :gender,
    :dateOfBirth,
    :issuingState,
    :nationality,
    :identificationNumber,
    :dateOfExpiry,
    :documentType
  ]

  @type t :: %__MODULE__{
          :givenName => String.t(),
          :lastName => String.t(),
          :gender => String.t(),
          :dateOfBirth => Date.t(),
          :issuingState => String.t(),
          :nationality => String.t(),
          :identificationNumber => String.t(),
          :dateOfExpiry => Date.t(),
          :documentType => String.t()
        }

  def decode(value) do
    value
  end
end
