# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.Name do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :fullName,
    :givenName,
    :languageCode,
    :lastName,
    :originalScript,
    :prefix,
    :suffix,
    :type
  ]

  @type t :: %__MODULE__{
          :fullName => String.t(),
          :givenName => String.t() | nil,
          :languageCode => ExWorldCheck.Model.LanguageCode.t() | nil,
          :lastName => String.t() | nil,
          :originalScript => String.t() | nil,
          :prefix => String.t() | nil,
          :suffix => String.t() | nil,
          :type => String.t()
        }
end

defimpl Poison.Decoder, for: ExWorldCheck.Model.Name do
  import ExWorldCheck.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:languageCode, :struct, ExWorldCheck.Model.LanguageCode, options)
  end
end
