# NOTE: This file is auto generated by OpenAPI Generator 7.13.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.Name do
  @moduledoc """

  """

  @derive JSON.Encoder
  defstruct [
    :fullName,
    :givenName,
    :languageCode,
    :lastName,
    :originalScript,
    :prefix,
    :suffix,
    :type
  ]

  @type t :: %__MODULE__{
          :fullName => String.t(),
          :givenName => String.t() | nil,
          :languageCode => ExWorldCheck.Model.LanguageCode.t() | nil,
          :lastName => String.t() | nil,
          :originalScript => String.t() | nil,
          :prefix => String.t() | nil,
          :suffix => String.t() | nil,
          :type => String.t()
        }

  alias ExWorldCheck.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:languageCode, :struct, ExWorldCheck.Model.LanguageCode)
  end
end
