# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.NewCaseAllOf do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :groupId,
    :entityType
  ]

  @type t :: %__MODULE__{
          :groupId => String.t(),
          :entityType => String.t()
        }
end

defimpl Poison.Decoder, for: ExWorldCheck.Model.NewCaseAllOf do
  def decode(value, _options) do
    value
  end
end
