# NOTE: This file is auto generated by OpenAPI Generator 7.13.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.OngoingScreeningRequest do
  @moduledoc """
  Request containing ongoing screening details
  """

  @derive JSON.Encoder
  defstruct [
    :providerTypes,
    :note
  ]

  @type t :: %__MODULE__{
          :providerTypes => [ExWorldCheck.Model.OngoingScreeningProviderType.t()] | nil,
          :note => String.t() | nil
        }

  alias ExWorldCheck.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :providerTypes,
      :list,
      ExWorldCheck.Model.OngoingScreeningProviderType
    )
  end
end
