# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.OngoingScreeningUpdateSearchResponseAllOf do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :results
  ]

  @type t :: %__MODULE__{
          :results => [ExWorldCheck.Model.OngoingScreeningUpdate.t()]
        }
end

defimpl Poison.Decoder, for: ExWorldCheck.Model.OngoingScreeningUpdateSearchResponseAllOf do
  import ExWorldCheck.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:results, :list, ExWorldCheck.Model.OngoingScreeningUpdate, options)
  end
end
