# NOTE: This file is auto generated by OpenAPI Generator 7.13.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.OngoingScreeningUpdateSearchResponse do
  @moduledoc """
  Search response containing a collection of `OngoingScreeningUpdate` s. Extends [SearchResponse](#SearchResponse). 
  """

  @derive JSON.Encoder
  defstruct [
    :query,
    :sort,
    :pagination,
    :totalResultCount,
    :results
  ]

  @type t :: %__MODULE__{
          :query => String.t() | nil,
          :sort => [ExWorldCheck.Model.SortCriterion.t()] | nil,
          :pagination => ExWorldCheck.Model.PaginationResponse.t() | nil,
          :totalResultCount => integer(),
          :results => [ExWorldCheck.Model.OngoingScreeningUpdate.t()]
        }

  alias ExWorldCheck.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:sort, :list, ExWorldCheck.Model.SortCriterion)
    |> Deserializer.deserialize(:pagination, :struct, ExWorldCheck.Model.PaginationResponse)
    |> Deserializer.deserialize(:results, :list, ExWorldCheck.Model.OngoingScreeningUpdate)
  end
end
