# NOTE: This file is auto generated by OpenAPI Generator 7.13.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.OrganisationSecondaryFields do
  @moduledoc """
  Secondary fields defined for entity type organisation and it is referenced from EDDRequestAuditDetails
  """

  @derive JSON.Encoder
  defstruct [
    :registeredCountry
  ]

  @type t :: %__MODULE__{
          :registeredCountry => String.t() | nil
        }

  def decode(value) do
    value
  end
end
