# NOTE: This file is auto generated by OpenAPI Generator 7.13.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.PaginationResponse do
  @moduledoc """
  Outbound - used to describe paginated partial result sets
  """

  @derive JSON.Encoder
  defstruct [
    :currentPage,
    :itemsPerPage,
    :totalItems
  ]

  @type t :: %__MODULE__{
          :currentPage => integer(),
          :itemsPerPage => integer(),
          :totalItems => integer() | nil
        }

  def decode(value) do
    value
  end
end
