# NOTE: This file is auto generated by OpenAPI Generator 7.13.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.Pagination do
  @moduledoc """
  Inbound - the pagination to apply to the query.
  """

  @derive JSON.Encoder
  defstruct [
    :currentPage,
    :itemsPerPage
  ]

  @type t :: %__MODULE__{
          :currentPage => integer(),
          :itemsPerPage => integer()
        }

  def decode(value) do
    value
  end
end
