# NOTE: This file is auto generated by OpenAPI Generator 7.13.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.ParentCaseDetailsChangedEventDetails do
  @moduledoc """
  Audit details which contains information about a change to the parent case. Extends [AbstractAuditDetails](#AbstractAuditDetails).
  """

  @derive JSON.Encoder
  defstruct [
    :detailsType,
    :externalId,
    :caseName,
    :previousExternalId,
    :previousCaseName
  ]

  @type t :: %__MODULE__{
          :detailsType => String.t(),
          :externalId => String.t(),
          :caseName => String.t(),
          :previousExternalId => String.t(),
          :previousCaseName => String.t()
        }

  def decode(value) do
    value
  end
end
