# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.ParentCaseDetailsChangedEventDetailsAllOf do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :externalId,
    :caseName,
    :previousExternalId,
    :previousCaseName
  ]

  @type t :: %__MODULE__{
          :externalId => String.t(),
          :caseName => String.t(),
          :previousExternalId => String.t(),
          :previousCaseName => String.t()
        }
end

defimpl Poison.Decoder, for: ExWorldCheck.Model.ParentCaseDetailsChangedEventDetailsAllOf do
  def decode(value, _options) do
    value
  end
end
