# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.PepDetailsRequest do
  @moduledoc """
  A request containing defined the sort order for retrieved PEP roles details.
  """

  @derive [Poison.Encoder]
  defstruct [
    :sort
  ]

  @type t :: %__MODULE__{
          :sort => ExWorldCheck.Model.SortCriterion.t() | nil
        }
end

defimpl Poison.Decoder, for: ExWorldCheck.Model.PepDetailsRequest do
  import ExWorldCheck.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:sort, :struct, ExWorldCheck.Model.SortCriterion, options)
  end
end
