# NOTE: This file is auto generated by OpenAPI Generator 7.13.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.PepDetailsRequest do
  @moduledoc """
  A request containing defined the sort order for retrieved PEP roles details.
  """

  @derive JSON.Encoder
  defstruct [
    :sort
  ]

  @type t :: %__MODULE__{
          :sort => ExWorldCheck.Model.SortCriterion.t() | nil
        }

  alias ExWorldCheck.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:sort, :struct, ExWorldCheck.Model.SortCriterion)
  end
end
