# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.PepUpdatedDates do
  @moduledoc """
  Represents PEP details' state change dates.
  """

  @derive [Poison.Encoder]
  defstruct [
    :pepStatusUpdated,
    :pepRolesUpdated
  ]

  @type t :: %__MODULE__{
          :pepStatusUpdated => Date.t() | nil,
          :pepRolesUpdated => Date.t() | nil
        }
end

defimpl Poison.Decoder, for: ExWorldCheck.Model.PepUpdatedDates do
  import ExWorldCheck.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:pepStatusUpdated, :date, nil, options)
    |> deserialize(:pepRolesUpdated, :date, nil, options)
  end
end
