# NOTE: This file is auto generated by OpenAPI Generator 7.13.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.PepDetailsResponse do
  @moduledoc """
  Retrieves detailed information for \"Politically Exposed Person (PEP)\" category by given record ID.
  """

  @derive JSON.Encoder
  defstruct [
    :sort,
    :pepStatus,
    :updatedDates,
    :roleDetails
  ]

  @type t :: %__MODULE__{
          :sort => ExWorldCheck.Model.SortCriterion.t() | nil,
          :pepStatus => String.t() | nil,
          :updatedDates => ExWorldCheck.Model.PepUpdatedDates.t() | nil,
          :roleDetails => [ExWorldCheck.Model.RoleDetails.t()] | nil
        }

  alias ExWorldCheck.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:sort, :struct, ExWorldCheck.Model.SortCriterion)
    |> Deserializer.deserialize(:updatedDates, :struct, ExWorldCheck.Model.PepUpdatedDates)
    |> Deserializer.deserialize(:roleDetails, :list, ExWorldCheck.Model.RoleDetails)
  end
end
