# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.PepDetailsResponse do
  @moduledoc """
  Retrieves detailed information for \"Politically Exposed Person (PEP)\" category by given record ID.
  """

  @derive [Poison.Encoder]
  defstruct [
    :sort,
    :pepStatus,
    :updatedDates,
    :roleDetails
  ]

  @type t :: %__MODULE__{
          :sort => ExWorldCheck.Model.SortCriterion.t() | nil,
          :pepStatus => String.t() | nil,
          :updatedDates => ExWorldCheck.Model.PepUpdatedDates.t() | nil,
          :roleDetails => [ExWorldCheck.Model.RoleDetails.t()] | nil
        }
end

defimpl Poison.Decoder, for: ExWorldCheck.Model.PepDetailsResponse do
  import ExWorldCheck.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:sort, :struct, ExWorldCheck.Model.SortCriterion, options)
    |> deserialize(:updatedDates, :struct, ExWorldCheck.Model.PepUpdatedDates, options)
    |> deserialize(:roleDetails, :list, ExWorldCheck.Model.RoleDetails, options)
  end
end
