# NOTE: This file is auto generated by OpenAPI Generator 7.13.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.ProfileEntityType do
  @moduledoc """
  Profile Entity Type Enumeration.  The `Entity` subclasses corresponding to each type of entity are:  * `COUNTRY` : `CountryEntity` * `INDIVIDUAL` : `IndividualEntity` * `ORGANISATION` : `OrganisationEntity` * `VESSEL` : `VesselEntity` 
  """

  @derive JSON.Encoder
  defstruct []

  @type t :: %__MODULE__{}

  def decode(value) do
    value
  end
end
