# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.ProviderTypeDetails do
  @moduledoc """
  Details about the specific provider type.
  """

  @derive [Poison.Encoder]
  defstruct [
    :mediaCheck
  ]

  @type t :: %__MODULE__{
          :mediaCheck => ExWorldCheck.Model.MediaCheckCaseDetails.t()
        }
end

defimpl Poison.Decoder, for: ExWorldCheck.Model.ProviderTypeDetails do
  import ExWorldCheck.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:mediaCheck, :struct, ExWorldCheck.Model.MediaCheckCaseDetails, options)
  end
end
