# NOTE: This file is auto generated by OpenAPI Generator 7.13.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.ProviderTypeDetails do
  @moduledoc """
  Details about the specific provider type.
  """

  @derive JSON.Encoder
  defstruct [
    :mediaCheck
  ]

  @type t :: %__MODULE__{
          :mediaCheck => ExWorldCheck.Model.MediaCheckCaseDetails.t()
        }

  alias ExWorldCheck.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:mediaCheck, :struct, ExWorldCheck.Model.MediaCheckCaseDetails)
  end
end
