# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.ProviderSourceType do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :category,
    :identifier,
    :name
  ]

  @type t :: %__MODULE__{
          :category => ExWorldCheck.Model.ProviderSourceTypeCategoryDetail.t() | nil,
          :identifier => String.t() | nil,
          :name => String.t() | nil
        }
end

defimpl Poison.Decoder, for: ExWorldCheck.Model.ProviderSourceType do
  import ExWorldCheck.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :category,
      :struct,
      ExWorldCheck.Model.ProviderSourceTypeCategoryDetail,
      options
    )
  end
end
