# NOTE: This file is auto generated by OpenAPI Generator 7.13.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.Provider do
  @moduledoc """

  """

  @derive JSON.Encoder
  defstruct [
    :code,
    :identifier,
    :master,
    :name
  ]

  @type t :: %__MODULE__{
          :code => String.t() | nil,
          :identifier => String.t() | nil,
          :master => boolean() | nil,
          :name => String.t() | nil
        }

  def decode(value) do
    value
  end
end
