# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.ProviderDetail do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :code,
    :identifier,
    :master,
    :name,
    :sources
  ]

  @type t :: %__MODULE__{
          :code => String.t() | nil,
          :identifier => String.t() | nil,
          :master => boolean() | nil,
          :name => String.t() | nil,
          :sources => [ExWorldCheck.Model.ProviderSource.t()] | nil
        }
end

defimpl Poison.Decoder, for: ExWorldCheck.Model.ProviderDetail do
  import ExWorldCheck.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:sources, :list, ExWorldCheck.Model.ProviderSource, options)
  end
end
