# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.ProviderSource do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :abbreviation,
    :creationDate,
    :identifier,
    :importIdentifier,
    :name,
    :provider,
    :providerSourceStatus,
    :regionOfAuthority,
    :subscriptionCategory,
    :type
  ]

  @type t :: %__MODULE__{
          :abbreviation => String.t(),
          :creationDate => DateTime.t() | nil,
          :identifier => String.t(),
          :importIdentifier => String.t() | nil,
          :name => String.t(),
          :provider => ExWorldCheck.Model.Provider.t() | nil,
          :providerSourceStatus => String.t(),
          :regionOfAuthority => String.t() | nil,
          :subscriptionCategory => String.t() | nil,
          :type => ExWorldCheck.Model.ProviderSourceType.t()
        }
end

defimpl Poison.Decoder, for: ExWorldCheck.Model.ProviderSource do
  import ExWorldCheck.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:provider, :struct, ExWorldCheck.Model.Provider, options)
    |> deserialize(:type, :struct, ExWorldCheck.Model.ProviderSourceType, options)
  end
end
