# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.RelationshipIdentifiers do
  @moduledoc """
  Relationship identifer between cases
  """

  @derive [Poison.Encoder]
  defstruct [
    :sourceCaseSystemId,
    :targetCaseSystemId,
    :relationshipType
  ]

  @type t :: %__MODULE__{
          :sourceCaseSystemId => String.t() | nil,
          :targetCaseSystemId => String.t() | nil,
          :relationshipType => String.t() | nil
        }
end

defimpl Poison.Decoder, for: ExWorldCheck.Model.RelationshipIdentifiers do
  def decode(value, _options) do
    value
  end
end
