# NOTE: This file is auto generated by OpenAPI Generator 7.13.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.RelationshipIdentifiers do
  @moduledoc """
  Relationship identifer between cases
  """

  @derive JSON.Encoder
  defstruct [
    :sourceCaseSystemId,
    :targetCaseSystemId,
    :relationshipType
  ]

  @type t :: %__MODULE__{
          :sourceCaseSystemId => String.t() | nil,
          :targetCaseSystemId => String.t() | nil,
          :relationshipType => String.t() | nil
        }

  def decode(value) do
    value
  end
end
