# NOTE: This file is auto generated by OpenAPI Generator 7.13.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.Resolution do
  @moduledoc """
  Resolution details of a Result.
  """

  @derive JSON.Encoder
  defstruct [
    :statusId,
    :riskId,
    :reasonId,
    :resolutionRemark,
    :resolutionDate
  ]

  @type t :: %__MODULE__{
          :statusId => String.t() | nil,
          :riskId => String.t() | nil,
          :reasonId => String.t() | nil,
          :resolutionRemark => String.t() | nil,
          :resolutionDate => DateTime.t() | nil
        }

  def decode(value) do
    value
  end
end
