# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.ResolutionField do
  @moduledoc """
  Represents the ID, label and type for a Status, a Risk or a Reason.
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :label,
    :type
  ]

  @type t :: %__MODULE__{
          :id => String.t(),
          :label => String.t(),
          :type => ExWorldCheck.Model.ResolutionStatusType.t() | nil
        }
end

defimpl Poison.Decoder, for: ExWorldCheck.Model.ResolutionField do
  import ExWorldCheck.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:type, :struct, ExWorldCheck.Model.ResolutionStatusType, options)
  end
end
