# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.Resolution do
  @moduledoc """
  Resolution details of a Result.
  """

  @derive [Poison.Encoder]
  defstruct [
    :statusId,
    :riskId,
    :reasonId,
    :resolutionRemark,
    :resolutionDate
  ]

  @type t :: %__MODULE__{
          :statusId => String.t() | nil,
          :riskId => String.t() | nil,
          :reasonId => String.t() | nil,
          :resolutionRemark => String.t() | nil,
          :resolutionDate => DateTime.t() | nil
        }
end

defimpl Poison.Decoder, for: ExWorldCheck.Model.Resolution do
  def decode(value, _options) do
    value
  end
end
