# NOTE: This file is auto generated by OpenAPI Generator 7.13.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.ResolutionToolkitResponse do
  @moduledoc """
  Resolution toolkit settings applicable for a Group.
  """

  @derive JSON.Encoder
  defstruct [
    :groupId,
    :resolutionFields,
    :resolutionRules
  ]

  @type t :: %__MODULE__{
          :groupId => String.t(),
          :resolutionFields => ExWorldCheck.Model.ResolutionFields.t() | nil,
          :resolutionRules => %{optional(String.t()) => ExWorldCheck.Model.StatusRule.t()} | nil
        }

  alias ExWorldCheck.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:resolutionFields, :struct, ExWorldCheck.Model.ResolutionFields)
    |> Deserializer.deserialize(:resolutionRules, :map, ExWorldCheck.Model.StatusRule)
  end
end
