# NOTE: This file is auto generated by OpenAPI Generator 7.13.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.ResolutionField do
  @moduledoc """
  Represents the ID, label and type for a Status, a Risk or a Reason.
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :label,
    :type
  ]

  @type t :: %__MODULE__{
          :id => String.t(),
          :label => String.t(),
          :type => ExWorldCheck.Model.ResolutionStatusType.t() | nil
        }

  alias ExWorldCheck.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:type, :struct, ExWorldCheck.Model.ResolutionStatusType)
  end
end
