# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.ResolutionToolkitResponse do
  @moduledoc """
  Resolution toolkit settings applicable for a Group.
  """

  @derive [Poison.Encoder]
  defstruct [
    :groupId,
    :resolutionFields,
    :resolutionRules
  ]

  @type t :: %__MODULE__{
          :groupId => String.t(),
          :resolutionFields => ExWorldCheck.Model.ResolutionFields.t() | nil,
          :resolutionRules => %{optional(String.t()) => ExWorldCheck.Model.StatusRule.t()} | nil
        }
end

defimpl Poison.Decoder, for: ExWorldCheck.Model.ResolutionToolkitResponse do
  import ExWorldCheck.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:resolutionFields, :struct, ExWorldCheck.Model.ResolutionFields, options)
    |> deserialize(:resolutionRules, :map, ExWorldCheck.Model.StatusRule, options)
  end
end
