# NOTE: This file is auto generated by OpenAPI Generator 7.13.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.Review do
  @moduledoc """
  Review details of a Result.
  """

  @derive JSON.Encoder
  defstruct [
    :reviewRequired,
    :reviewRequiredDate,
    :reviewRemark,
    :reviewDate
  ]

  @type t :: %__MODULE__{
          :reviewRequired => boolean() | nil,
          :reviewRequiredDate => DateTime.t() | nil,
          :reviewRemark => String.t() | nil,
          :reviewDate => DateTime.t() | nil
        }

  def decode(value) do
    value
  end
end
