# NOTE: This file is auto generated by OpenAPI Generator 7.13.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.RoleDetails do
  @moduledoc """
  Represents the role details.
  """

  @derive JSON.Encoder
  defstruct [
    :title,
    :level,
    :position,
    :biography,
    :status,
    :roleTermStartDate,
    :roleTermEndDate
  ]

  @type t :: %__MODULE__{
          :title => String.t() | nil,
          :level => String.t() | nil,
          :position => String.t() | nil,
          :biography => String.t() | nil,
          :status => ExWorldCheck.Model.RoleStatusType.t() | nil,
          :roleTermStartDate => Date.t() | nil,
          :roleTermEndDate => Date.t() | nil
        }

  alias ExWorldCheck.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:status, :struct, ExWorldCheck.Model.RoleStatusType)
  end
end
