# NOTE: This file is auto generated by OpenAPI Generator 7.13.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.Role do
  @moduledoc """

  """

  @derive JSON.Encoder
  defstruct [
    :end,
    :location,
    :source,
    :start,
    :title,
    :type
  ]

  @type t :: %__MODULE__{
          :end => String.t() | nil,
          :location => String.t() | nil,
          :source => ExWorldCheck.Model.ProviderSource.t() | nil,
          :start => String.t() | nil,
          :title => String.t() | nil,
          :type => String.t() | nil
        }

  alias ExWorldCheck.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:source, :struct, ExWorldCheck.Model.ProviderSource)
  end
end
