# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.Role do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :end,
    :location,
    :source,
    :start,
    :title,
    :type
  ]

  @type t :: %__MODULE__{
          :end => String.t() | nil,
          :location => String.t() | nil,
          :source => ExWorldCheck.Model.ProviderSource.t() | nil,
          :start => String.t() | nil,
          :title => String.t() | nil,
          :type => String.t() | nil
        }
end

defimpl Poison.Decoder, for: ExWorldCheck.Model.Role do
  import ExWorldCheck.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:source, :struct, ExWorldCheck.Model.ProviderSource, options)
  end
end
