# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.RoleDetails do
  @moduledoc """
  Represents the role details.
  """

  @derive [Poison.Encoder]
  defstruct [
    :title,
    :level,
    :position,
    :biography,
    :status,
    :roleTermStartDate,
    :roleTermEndDate
  ]

  @type t :: %__MODULE__{
          :title => String.t() | nil,
          :level => String.t() | nil,
          :position => String.t() | nil,
          :biography => String.t() | nil,
          :status => ExWorldCheck.Model.RoleStatusType.t() | nil,
          :roleTermStartDate => Date.t() | nil,
          :roleTermEndDate => Date.t() | nil
        }
end

defimpl Poison.Decoder, for: ExWorldCheck.Model.RoleDetails do
  import ExWorldCheck.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:status, :struct, ExWorldCheck.Model.RoleStatusType, options)
    |> deserialize(:roleTermStartDate, :date, nil, options)
    |> deserialize(:roleTermEndDate, :date, nil, options)
  end
end
