# NOTE: This file is auto generated by OpenAPI Generator 7.13.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.ScreeningStatusResponse do
  @moduledoc """
  Contains status and aggregated screening result for each requested case. If 'requestFromScreenedDate' less than 'lastScreenedDate' then status equals 'NOT_SCREENED' else status equals 'SCREENED'. 
  """

  @derive JSON.Encoder
  defstruct [
    :caseSystemId,
    :screeningStatus,
    :requestFromScreenedDate,
    :lastScreenedDate,
    :providerSummaries
  ]

  @type t :: %__MODULE__{
          :caseSystemId => String.t(),
          :screeningStatus => String.t(),
          :requestFromScreenedDate => DateTime.t(),
          :lastScreenedDate => DateTime.t() | nil,
          :providerSummaries => %{
            optional(String.t()) => ExWorldCheck.Model.ProviderTypeSummaryResult.t()
          }
        }

  alias ExWorldCheck.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :providerSummaries,
      :map,
      ExWorldCheck.Model.ProviderTypeSummaryResult
    )
  end
end
