# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.ScreeningStatusRequestCollection do
  @moduledoc """
  Collection  of 'ScreeningStatusRequest'. The maximum number of cases is configured in account settings. 
  """

  @derive [Poison.Encoder]
  defstruct [
    :screeningStatusRequests,
    :providerTypes
  ]

  @type t :: %__MODULE__{
          :screeningStatusRequests => [ExWorldCheck.Model.ScreeningStatusRequest.t()] | nil,
          :providerTypes => [ExWorldCheck.Model.ProviderType.t()] | nil
        }
end

defimpl Poison.Decoder, for: ExWorldCheck.Model.ScreeningStatusRequestCollection do
  import ExWorldCheck.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :screeningStatusRequests,
      :list,
      ExWorldCheck.Model.ScreeningStatusRequest,
      options
    )
    |> deserialize(:providerTypes, :list, ExWorldCheck.Model.ProviderType, options)
  end
end
