# NOTE: This file is auto generated by OpenAPI Generator 7.13.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.ScreenCaseAuditDetails do
  @moduledoc """
  Audit details for SCREENED_CASE action raised when a Case screening has been completed. Extends [AbstractAuditDetails](#AbstractAuditDetails).
  """

  @derive JSON.Encoder
  defstruct [
    :detailsType,
    :userId,
    :caseSystemId,
    :statusCode,
    :screeningState,
    :startScreeningDate,
    :noOfNewResults,
    :noOfReviewRequiredResults,
    :noOfExcludedResults,
    :noOfAutoResolvedResults,
    :providerTypes
  ]

  @type t :: %__MODULE__{
          :detailsType => String.t(),
          :userId => String.t(),
          :caseSystemId => String.t(),
          :statusCode => String.t(),
          :screeningState => String.t(),
          :startScreeningDate => DateTime.t(),
          :noOfNewResults => integer(),
          :noOfReviewRequiredResults => integer(),
          :noOfExcludedResults => integer(),
          :noOfAutoResolvedResults => integer(),
          :providerTypes => [ExWorldCheck.Model.ProviderType.t()]
        }

  alias ExWorldCheck.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:providerTypes, :list, ExWorldCheck.Model.ProviderType)
  end
end
