# NOTE: This file is auto generated by OpenAPI Generator 7.13.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.ScreeningStatusRequestCollection do
  @moduledoc """
  Collection  of 'ScreeningStatusRequest'. The maximum number of cases is configured in account settings. 
  """

  @derive JSON.Encoder
  defstruct [
    :screeningStatusRequests,
    :providerTypes
  ]

  @type t :: %__MODULE__{
          :screeningStatusRequests => [ExWorldCheck.Model.ScreeningStatusRequest.t()] | nil,
          :providerTypes => [ExWorldCheck.Model.ProviderType.t()] | nil
        }

  alias ExWorldCheck.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :screeningStatusRequests,
      :list,
      ExWorldCheck.Model.ScreeningStatusRequest
    )
    |> Deserializer.deserialize(:providerTypes, :list, ExWorldCheck.Model.ProviderType)
  end
end
