# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.ScreeningStatusRequest do
  @moduledoc """
  Contains 'caseSystemId' and presumptive screening timestamp which should be checked. 
  """

  @derive [Poison.Encoder]
  defstruct [
    :caseSystemId,
    :dateFrom
  ]

  @type t :: %__MODULE__{
          :caseSystemId => String.t() | nil,
          :dateFrom => DateTime.t() | nil
        }
end

defimpl Poison.Decoder, for: ExWorldCheck.Model.ScreeningStatusRequest do
  def decode(value, _options) do
    value
  end
end
