# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.ScreeningRequestAllOf do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :caseScreeningState,
    :startScreeningDate,
    :endScreeningDate
  ]

  @type t :: %__MODULE__{
          :caseScreeningState => %{optional(String.t()) => String.t()} | nil,
          :startScreeningDate => DateTime.t() | nil,
          :endScreeningDate => DateTime.t() | nil
        }
end

defimpl Poison.Decoder, for: ExWorldCheck.Model.ScreeningRequestAllOf do
  def decode(value, _options) do
    value
  end
end
