# NOTE: This file is auto generated by OpenAPI Generator 7.13.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.ScreeningStatusRequest do
  @moduledoc """
  Contains 'caseSystemId' and presumptive screening timestamp which should be checked. 
  """

  @derive JSON.Encoder
  defstruct [
    :caseSystemId,
    :dateFrom
  ]

  @type t :: %__MODULE__{
          :caseSystemId => String.t() | nil,
          :dateFrom => DateTime.t() | nil
        }

  def decode(value) do
    value
  end
end
