# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.SearchResponse do
  @moduledoc """
  Common fields used in search responses.  These fields are included in response types, and objects of this type are not returned directly.
  """

  @derive [Poison.Encoder]
  defstruct [
    :query,
    :sort,
    :pagination,
    :totalResultCount
  ]

  @type t :: %__MODULE__{
          :query => String.t() | nil,
          :sort => [ExWorldCheck.Model.SortCriterion.t()] | nil,
          :pagination => ExWorldCheck.Model.PaginationResponse.t() | nil,
          :totalResultCount => integer()
        }
end

defimpl Poison.Decoder, for: ExWorldCheck.Model.SearchResponse do
  import ExWorldCheck.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:sort, :list, ExWorldCheck.Model.SortCriterion, options)
    |> deserialize(:pagination, :struct, ExWorldCheck.Model.PaginationResponse, options)
  end
end
