# NOTE: This file is auto generated by OpenAPI Generator 7.13.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.SearchResponse do
  @moduledoc """
  Common fields used in search responses.  These fields are included in response types, and objects of this type are not returned directly.
  """

  @derive JSON.Encoder
  defstruct [
    :query,
    :sort,
    :pagination,
    :totalResultCount
  ]

  @type t :: %__MODULE__{
          :query => String.t() | nil,
          :sort => [ExWorldCheck.Model.SortCriterion.t()] | nil,
          :pagination => ExWorldCheck.Model.PaginationResponse.t() | nil,
          :totalResultCount => integer()
        }

  alias ExWorldCheck.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:sort, :list, ExWorldCheck.Model.SortCriterion)
    |> Deserializer.deserialize(:pagination, :struct, ExWorldCheck.Model.PaginationResponse)
  end
end
