# NOTE: This file is auto generated by OpenAPI Generator 7.13.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.SecondaryFieldsByEntity do
  @moduledoc """
  Wrapper which contains secondary fields grouped by CaseEntityType.
  """

  @derive JSON.Encoder
  defstruct [
    :secondaryFieldsByEntity
  ]

  @type t :: %__MODULE__{
          :secondaryFieldsByEntity => %{
            optional(String.t()) => [ExWorldCheck.Model.FieldDefinition.t()]
          }
        }

  def decode(value) do
    value
  end
end
