# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.SortCriterion do
  @moduledoc """
  Sort specification
  """

  @derive [Poison.Encoder]
  defstruct [
    :columnName,
    :order
  ]

  @type t :: %__MODULE__{
          :columnName => String.t() | nil,
          :order => String.t() | nil
        }
end

defimpl Poison.Decoder, for: ExWorldCheck.Model.SortCriterion do
  def decode(value, _options) do
    value
  end
end
