# NOTE: This file is auto generated by OpenAPI Generator 7.13.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.SortCriterion do
  @moduledoc """
  Sort specification
  """

  @derive JSON.Encoder
  defstruct [
    :columnName,
    :order
  ]

  @type t :: %__MODULE__{
          :columnName => String.t() | nil,
          :order => String.t() | nil
        }

  def decode(value) do
    value
  end
end
