# NOTE: This file is auto generated by OpenAPI Generator 7.13.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.StatusRule do
  @moduledoc """
  Represents the rules that should be applied when resolving a Result with a specific Status.
  """

  @derive JSON.Encoder
  defstruct [
    :reasons,
    :remarkRequired,
    :reasonRequired,
    :risks
  ]

  @type t :: %__MODULE__{
          :reasons => [String.t()],
          :remarkRequired => boolean(),
          :reasonRequired => boolean(),
          :risks => [String.t()]
        }

  def decode(value) do
    value
  end
end
