# NOTE: This file is auto generated by OpenAPI Generator 7.13.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.TypeAvailableSelected do
  @moduledoc """
  Represents a type and also tells whether it is available and whether it should be selected by default
  """

  @derive JSON.Encoder
  defstruct [
    :selected,
    :type,
    :available
  ]

  @type t :: %__MODULE__{
          :selected => boolean() | nil,
          :type => String.t() | nil,
          :available => boolean() | nil
        }

  def decode(value) do
    value
  end
end
