# NOTE: This file is auto generated by OpenAPI Generator 7.13.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.UserSummary do
  @moduledoc """

  """

  @derive JSON.Encoder
  defstruct [
    :userId,
    :fullName,
    :firstName,
    :lastName,
    :email,
    :status
  ]

  @type t :: %__MODULE__{
          :userId => String.t(),
          :fullName => String.t(),
          :firstName => String.t() | nil,
          :lastName => String.t() | nil,
          :email => String.t(),
          :status => ExWorldCheck.Model.StatusType.t()
        }

  alias ExWorldCheck.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:status, :struct, ExWorldCheck.Model.StatusType)
  end
end
