# NOTE: This file is auto generated by OpenAPI Generator 7.13.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.VerifyPassportAuditDetails do
  @moduledoc """
  Audit details for VERIFY_PASSPORT_DETAILS action raised when passport details are verified. Extends [AbstractAuditDetails](#AbstractAuditDetails).
  """

  @derive JSON.Encoder
  defstruct [
    :detailsType,
    :validity,
    :mrzLine1,
    :mrzLine2,
    :mrzLine3,
    :givenName,
    :lastName,
    :gender,
    :issuingState,
    :nationality,
    :dateOfBirth,
    :documentType,
    :idNumber,
    :expiryDate
  ]

  @type t :: %__MODULE__{
          :detailsType => String.t(),
          :validity => ExWorldCheck.Model.PassportCheckValidityType.t(),
          :mrzLine1 => String.t(),
          :mrzLine2 => String.t(),
          :mrzLine3 => String.t(),
          :givenName => String.t(),
          :lastName => String.t(),
          :gender => String.t(),
          :issuingState => String.t(),
          :nationality => String.t(),
          :dateOfBirth => Date.t(),
          :documentType => String.t(),
          :idNumber => String.t(),
          :expiryDate => Date.t()
        }

  alias ExWorldCheck.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:validity, :struct, ExWorldCheck.Model.PassportCheckValidityType)
  end
end
