# NOTE: This file is auto generated by OpenAPI Generator 7.13.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.WatchlistDataSet do
  @moduledoc """

  """

  @derive JSON.Encoder
  defstruct [
    :entityCreateOrUpdate,
    :entityDelete,
    :entitySupersede,
    :entityPurge
  ]

  @type t :: %__MODULE__{
          :entityCreateOrUpdate => [ExWorldCheck.Model.Entity.t()] | nil,
          :entityDelete => [ExWorldCheck.Model.EntityDelete.t()] | nil,
          :entitySupersede => [ExWorldCheck.Model.EntitySupersede.t()] | nil,
          :entityPurge => [ExWorldCheck.Model.EntityPurge.t()] | nil
        }

  alias ExWorldCheck.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:entityCreateOrUpdate, :list, ExWorldCheck.Model.Entity)
    |> Deserializer.deserialize(:entityDelete, :list, ExWorldCheck.Model.EntityDelete)
    |> Deserializer.deserialize(:entitySupersede, :list, ExWorldCheck.Model.EntitySupersede)
    |> Deserializer.deserialize(:entityPurge, :list, ExWorldCheck.Model.EntityPurge)
  end
end
