# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.WatchlistResponse do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :errors
  ]

  @type t :: %__MODULE__{
          :errors => [ExWorldCheck.Model.Error.t()]
        }
end

defimpl Poison.Decoder, for: ExWorldCheck.Model.WatchlistResponse do
  import ExWorldCheck.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:errors, :list, ExWorldCheck.Model.Error, options)
  end
end
