# NOTE: This file is auto generated by OpenAPI Generator 7.13.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.WatchlistResponse do
  @moduledoc """

  """

  @derive JSON.Encoder
  defstruct [
    :errors
  ]

  @type t :: %__MODULE__{
          :errors => [ExWorldCheck.Model.Error.t()]
        }

  alias ExWorldCheck.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:errors, :list, ExWorldCheck.Model.Error)
  end
end
