# NOTE: This file is auto generated by OpenAPI Generator 7.13.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ExWorldCheck.Model.Weblink do
  @moduledoc """

  """

  @derive JSON.Encoder
  defstruct [
    :caption,
    :uri,
    :tags
  ]

  @type t :: %__MODULE__{
          :caption => String.t() | nil,
          :uri => String.t() | nil,
          :tags => [String.t()] | nil
        }

  def decode(value) do
    value
  end
end
